In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
import unicodecsv as csv
from io import BytesIO
f = BytesIO()
w = csv.writer(f, encoding='utf-8')
_ = w.writerow((u'é', u'ñ'))
_ = f.seek(0)
r = csv.reader(f, encoding='utf-8')
next(r) == [u'é', u'ñ']
True

True

In [3]:
import glob
glob.glob("C:/Users/JESICA/Base Accidentes INEGI/*.csv")

['C:/Users/JESICA/Base Accidentes INEGI\\ATUS_2014.csv',
 'C:/Users/JESICA/Base Accidentes INEGI\\ATUS_2015.csv',
 'C:/Users/JESICA/Base Accidentes INEGI\\ATUS_2016.csv',
 'C:/Users/JESICA/Base Accidentes INEGI\\ATUS_2017.csv',
 'C:/Users/JESICA/Base Accidentes INEGI\\ATUS_2018.csv']

In [4]:
accidentesnacional=pd.DataFrame()
for x in glob.glob("C:/Users/JESICA/Base Accidentes INEGI/*.csv"):
    df=pd.read_csv(x,sep = ',', encoding="utf-8-sig")
    accidentesnacional=accidentesnacional.append(df,ignore_index=True)

In [5]:
accidentesnacional.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1872072 entries, 0 to 1872071
Data columns (total 42 columns):
EDO           int64
MES           int64
ANIO          int64
MPIO          int64
HORA          int64
MINUTOS       int64
DIA           int64
DIASEMANA     int64
URBANA        int64
SUBURBANA     int64
TIPACCID      int64
AUTOMOVIL     int64
CAMPASAJ      int64
MICROBUS      int64
PASCAMION     int64
OMNIBUS       int64
TRANVIA       int64
CAMIONETA     int64
CAMION        int64
TRACTOR       int64
FERROCARRI    int64
MOTOCICLET    int64
BICICLETA     int64
OTROVEHIC     int64
CAUSAACCI     int64
CAPAROD       int64
SEXO          int64
ALIENTO       int64
CINTURON      int64
EDAD          int64
CONDMUERTO    int64
CONDHERIDO    int64
PASAMUERTO    int64
PASAHERIDO    int64
PEATMUERTO    int64
PEATHERIDO    int64
CICLMUERTO    int64
CICLHERIDO    int64
OTROMUERTO    int64
OTROHERIDO    int64
NEMUERTO      int64
NEHERIDO      int64
dtypes: int64(42)
memory usage: 599.9 MB

In [6]:
accidentesnacional

,EDO,MES,ANIO,MPIO,HORA,MINUTOS,DIA,DIASEMANA,URBANA,SUBURBANA,...,PASAMUERTO,PASAHERIDO,PEATMUERTO,PEATHERIDO,CICLMUERTO,CICLHERIDO,OTROMUERTO,OTROHERIDO,NEMUERTO,NEHERIDO
0,1,1,2014,5,20,30,2,4,0,2,...,0,0,0,0,0,0,0,0,0,0
1,1,1,2014,5,9,15,3,5,1,0,...,0,0,0,0,0,0,0,0,0,0
2,1,1,2014,5,9,0,3,5,1,0,...,0,0,0,0,0,0,0,0,0,0
3,1,1,2014,5,9,0,3,5,1,0,...,0,0,0,0,0,0,0,0,0,0
4,1,1,2014,5,23,20,5,7,2,0,...,0,0,0,0,0,0,0,0,0,0
5,1,1,2014,5,13,25,6,1,2,0,...,0,0,0,0,0,0,0,0,0,0
6,1,1,2014,5,1,13,7,2,1,0,...,0,0,0,0,0,0,0,0,0,0
7,1,1,2014,5,11,30,8,3,2,0,...,0,0,0,0,0,0,0,0,0,0
8,1,1,2014,5,13,10,8,3,2,0,...,0,0,0,0,0,0,0,0,0,0
9,1,1,2014,5,8,0,10,5,2,0,...,0,0,0,0,0,0,0,0,0,0
10,1,1,2014,5,14,20,11,6,1,0,...,0,0,0,0,0,0,0,0,0,0
11,1,1,2014,5,1,30,12,7,2,0,...,0,0,0,0,0,0,0,0,0,0
12,1,1,2014,5,6,0,12,7,1,0,...,0,0,0,0,0,0,0,0,0,0
13,1,1,2014,5,21,40,13,1,2,0,...,0,0,0,0,0,0,0,0,0,0
14,1,1,2014,5,23,10,16,4,1,0,...,0,0,0,0,0,0,0,0,0,0
15,1,1,2014,5,16,21,17,5,2,0,...,0,0,0,0,0,0,0,0,0,0
16,1,1,2014,5,21,15,17,5,1,0,...,0,0,0,0,0,0,0,0,0,0
17,1,1,2014,5,16,10,18,6,0,1,...,0,0,0,0,0,0,0,0,0,0
18,1,1,2014,5,19,0,18,6,1,0,...,0,0,0,0,0,0,0,0,0,0
19,1,1,2014,5,0,30,20,1,1,0,...,0,0,0,0,0,0,0,0,0,0
20,1,1,2014,5,18,30,20,1,2,0,...,0,0,0,0,0,0,0,0,0,0
21,1,1,2014,5,16,5,22,3,2,0,...,0,0,0,1,0,0,0,0,0,0
22,1,1,2014,5,18,30,24,5,1,0,...,0,0,0,0,0,0,0,0,0,0
23,1,1,2014,5,9,30,26,7,1,0,...,0,0,0,0,0,0,0,0,0,0
24,1,1,2014,5,8,30,27,1,1,0,...,0,0,0,0,0,0,0,0,0,0
25,1,1,2014,5,16,0,27,1,2,0,...,0,0,0,0,0,0,0,0,0,0
26,1,1,2014,5,17,50,29,3,2,0,...,0,0,0,0,0,0,0,0,0,0
27,1,1,2014,5,12,15,31,5,1,0,...,0,0,0,0,0,0,0,0,0,0
28,1,2,2014,5,1,15,2,7,2,0,...,0,0,0,0,0,0,0,0,0,0
29,1,2,2014,5,9,20,5,3,2,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1872042,14,12,2018,77,6,20,7,5,0,2,...,0,0,0,0,0,0,0,0,0,0
1872043,14,12,2018,77,12,25,19,3,1,0,...,0,0,0,0,0,0,0,0,0,0
1872044,12,12,2018,43,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1872045,12,12,2018,78,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1872046,12,12,2018,31,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1872047,12,12,2018,63,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1872048,12,12,2018,9,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1872049,15,12,2018,12,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1872050,15,12,2018,14,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1872051,15,12,2018,88,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1872052,15,12,2018,19,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1872053,15,12,2018,29,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1872054,15,12,2018,43,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1872055,15,12,2018,45,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1872056,15,12,2018,60,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1872057,15,12,2018,62,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1872058,15,12,2018,67,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1872059,15,12,2018,101,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1872060,15,12,2018,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1872061,15,12,2018,6,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1872062,15,12,2018,7,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1872063,15,12,2018,76,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1872064,15,12,2018,115,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1872065,15,12,2018,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1872066,15,12,2018,48,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1872067,15,12,2018,58,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1872068,15,12,2018,98,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1872069,15,12,2018,110,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1872070,15,12,2018,118,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1872071,15,12,2018,55,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
accidentesnacional.count()

EDO           1872072
MES           1872072
ANIO          1872072
MPIO          1872072
HORA          1872072
MINUTOS       1872072
DIA           1872072
DIASEMANA     1872072
URBANA        1872072
SUBURBANA     1872072
TIPACCID      1872072
AUTOMOVIL     1872072
CAMPASAJ      1872072
MICROBUS      1872072
PASCAMION     1872072
OMNIBUS       1872072
TRANVIA       1872072
CAMIONETA     1872072
CAMION        1872072
TRACTOR       1872072
FERROCARRI    1872072
MOTOCICLET    1872072
BICICLETA     1872072
OTROVEHIC     1872072
CAUSAACCI     1872072
CAPAROD       1872072
SEXO          1872072
ALIENTO       1872072
CINTURON      1872072
EDAD          1872072
CONDMUERTO    1872072
CONDHERIDO    1872072
PASAMUERTO    1872072
PASAHERIDO    1872072
PEATMUERTO    1872072
PEATHERIDO    1872072
CICLMUERTO    1872072
CICLHERIDO    1872072
OTROMUERTO    1872072
OTROHERIDO    1872072
NEMUERTO      1872072
NEHERIDO      1872072
dtype: int64

In [8]:
accidentesnacional = accidentesnacional.dropna(how='any')

In [9]:
accidentesnacional.count()

EDO           1872072
MES           1872072
ANIO          1872072
MPIO          1872072
HORA          1872072
MINUTOS       1872072
DIA           1872072
DIASEMANA     1872072
URBANA        1872072
SUBURBANA     1872072
TIPACCID      1872072
AUTOMOVIL     1872072
CAMPASAJ      1872072
MICROBUS      1872072
PASCAMION     1872072
OMNIBUS       1872072
TRANVIA       1872072
CAMIONETA     1872072
CAMION        1872072
TRACTOR       1872072
FERROCARRI    1872072
MOTOCICLET    1872072
BICICLETA     1872072
OTROVEHIC     1872072
CAUSAACCI     1872072
CAPAROD       1872072
SEXO          1872072
ALIENTO       1872072
CINTURON      1872072
EDAD          1872072
CONDMUERTO    1872072
CONDHERIDO    1872072
PASAMUERTO    1872072
PASAHERIDO    1872072
PEATMUERTO    1872072
PEATHERIDO    1872072
CICLMUERTO    1872072
CICLHERIDO    1872072
OTROMUERTO    1872072
OTROHERIDO    1872072
NEMUERTO      1872072
NEHERIDO      1872072
dtype: int64

In [10]:
accidentesnacional['DIA'].value_counts()

1     72856
15    63235
14    62825
10    61745
18    61701
13    61664
16    61606
17    61433
12    61312
11    61028
8     61000
4     60839
7     60804
9     60711
21    60627
3     60506
2     60324
22    60238
23    60224
6     60145
5     60135
20    60074
19    60066
28    60055
24    59718
27    58545
25    58186
26    58028
29    54769
30    54614
31    33170
0     16426
32     3463
Name: DIA, dtype: int64

In [11]:
accidentesnacional['MES'].value_counts()

12    165359
3     162217
10    161929
5     160460
11    159120
8     154795
6     153144
1     151642
7     151163
4     151118
9     150925
2     150200
Name: MES, dtype: int64

In [12]:
accidentesnacional['ANIO'].value_counts()

2015    382066
2018    381593
2014    380573
2017    367789
2016    360051
Name: ANIO, dtype: int64

In [13]:
accidentesnacional['EDO'].value_counts()

19    401756
14    172276
8     147526
11     95106
2      75724
5      73071
26     70005
22     68256
28     67468
15     63646
9      62077
16     60989
21     49245
30     46362
17     45907
25     42593
23     32629
6      29581
31     29132
10     28717
20     25985
24     24261
1      20182
12     19295
3      19062
13     18281
4      18112
29     15127
7      14100
27     13235
32     12601
18      9765
Name: EDO, dtype: int64

In [14]:
accidentesnacional['MPIO'].value_counts()

39     236502
19     111419
6       73266
4       58275
5       57660
14      54874
46      51429
1       50274
18      43777
7       42494
2       42081
17      41324
20      39159
21      38652
3       37542
120     36441
37      35910
26      35087
53      33559
35      32450
33      30833
30      28689
114     28445
48      26033
10      23625
32      23178
27      22155
28      21401
11      21321
9       21018
        ...
275        12
276        12
280        12
282        12
283        12
284        12
569        12
287        12
288        12
289        12
290        12
268        12
267        12
265        12
255        12
247        12
249        12
250        12
251        12
252        12
253        12
256        12
264        12
257        12
258        12
259        12
260        12
261        12
263        12
285        12
Name: MPIO, Length: 570, dtype: int64

In [15]:
accidentesnacional['DIASEMANA'].value_counts()

6    296740
5    285097
7    261655
1    257519
4    252343
3    249748
2    249081
0     16426
8      3463
Name: DIASEMANA, dtype: int64

In [16]:
accidentesnacional = accidentesnacional[accidentesnacional.DIA != 0]

In [17]:
accidentesnacional = accidentesnacional[accidentesnacional.DIA != 32]

In [18]:
accidentesnacional["DIA"].value_counts()

1     72856
15    63235
14    62825
10    61745
18    61701
13    61664
16    61606
17    61433
12    61312
11    61028
8     61000
4     60839
7     60804
9     60711
21    60627
3     60506
2     60324
22    60238
23    60224
6     60145
5     60135
20    60074
19    60066
28    60055
24    59718
27    58545
25    58186
26    58028
29    54769
30    54614
31    33170
Name: DIA, dtype: int64

In [19]:
accidentesnacional = accidentesnacional[accidentesnacional.DIASEMANA != 0]

In [20]:
accidentesnacional = accidentesnacional[accidentesnacional.DIASEMANA != 8]

In [21]:
accidentesnacional["DIASEMANA"].value_counts()

6    296740
5    285097
7    261655
1    257519
4    252343
3    249748
2    249081
Name: DIASEMANA, dtype: int64

In [22]:
accidentesnacional.count()

EDO           1852183
MES           1852183
ANIO          1852183
MPIO          1852183
HORA          1852183
MINUTOS       1852183
DIA           1852183
DIASEMANA     1852183
URBANA        1852183
SUBURBANA     1852183
TIPACCID      1852183
AUTOMOVIL     1852183
CAMPASAJ      1852183
MICROBUS      1852183
PASCAMION     1852183
OMNIBUS       1852183
TRANVIA       1852183
CAMIONETA     1852183
CAMION        1852183
TRACTOR       1852183
FERROCARRI    1852183
MOTOCICLET    1852183
BICICLETA     1852183
OTROVEHIC     1852183
CAUSAACCI     1852183
CAPAROD       1852183
SEXO          1852183
ALIENTO       1852183
CINTURON      1852183
EDAD          1852183
CONDMUERTO    1852183
CONDHERIDO    1852183
PASAMUERTO    1852183
PASAHERIDO    1852183
PEATMUERTO    1852183
PEATHERIDO    1852183
CICLMUERTO    1852183
CICLHERIDO    1852183
OTROMUERTO    1852183
OTROHERIDO    1852183
NEMUERTO      1852183
NEHERIDO      1852183
dtype: int64

In [23]:
accidentesnacional = accidentesnacional.dropna(how='any')

In [24]:
accidentesnacional.count()

EDO           1852183
MES           1852183
ANIO          1852183
MPIO          1852183
HORA          1852183
MINUTOS       1852183
DIA           1852183
DIASEMANA     1852183
URBANA        1852183
SUBURBANA     1852183
TIPACCID      1852183
AUTOMOVIL     1852183
CAMPASAJ      1852183
MICROBUS      1852183
PASCAMION     1852183
OMNIBUS       1852183
TRANVIA       1852183
CAMIONETA     1852183
CAMION        1852183
TRACTOR       1852183
FERROCARRI    1852183
MOTOCICLET    1852183
BICICLETA     1852183
OTROVEHIC     1852183
CAUSAACCI     1852183
CAPAROD       1852183
SEXO          1852183
ALIENTO       1852183
CINTURON      1852183
EDAD          1852183
CONDMUERTO    1852183
CONDHERIDO    1852183
PASAMUERTO    1852183
PASAHERIDO    1852183
PEATMUERTO    1852183
PEATHERIDO    1852183
CICLMUERTO    1852183
CICLHERIDO    1852183
OTROMUERTO    1852183
OTROHERIDO    1852183
NEMUERTO      1852183
NEHERIDO      1852183
dtype: int64

In [25]:
accidentesnacional['DIAs'] = accidentesnacional['DIA'].astype(str)
accidentesnacional['MESs'] = accidentesnacional['MES'].astype(str)
accidentesnacional['ANIOs'] = accidentesnacional['ANIO'].astype(str)

In [26]:
accidentesnacional['fechaaccidente'] = accidentesnacional['DIAs']+'/'+accidentesnacional['MESs']+'/'+accidentesnacional['ANIOs']

In [27]:
accidentesnacional.head()

,EDO,MES,ANIO,MPIO,HORA,MINUTOS,DIA,DIASEMANA,URBANA,SUBURBANA,...,CICLMUERTO,CICLHERIDO,OTROMUERTO,OTROHERIDO,NEMUERTO,NEHERIDO,DIAs,MESs,ANIOs,fechaaccidente
0,1,1,2014,5,20,30,2,4,0,2,...,0,0,0,0,0,0,2,1,2014,2/1/2014
1,1,1,2014,5,9,15,3,5,1,0,...,0,0,0,0,0,0,3,1,2014,3/1/2014
2,1,1,2014,5,9,0,3,5,1,0,...,0,0,0,0,0,0,3,1,2014,3/1/2014
3,1,1,2014,5,9,0,3,5,1,0,...,0,0,0,0,0,0,3,1,2014,3/1/2014
4,1,1,2014,5,23,20,5,7,2,0,...,0,0,0,0,0,0,5,1,2014,5/1/2014

In [28]:
accidentesnacional['fechaaccidente'].value_counts()

1/3/2014      1520
1/4/2017      1489
14/2/2014     1426
1/2/2014      1412
12/12/2015    1408
1/12/2017     1402
14/11/2015    1389
1/11/2014     1375
1/7/2017      1366
1/12/2018     1366
1/3/2015      1361
1/11/2017     1350
1/12/2016     1341
16/12/2017    1333
15/3/2014     1320
15/12/2018    1315
1/9/2017      1314
15/12/2017    1313
1/8/2015      1309
1/11/2015     1308
28/11/2015    1307
20/12/2014    1306
5/12/2014     1306
4/4/2014      1306
13/12/2014    1306
1/1/2018      1305
1/12/2014     1305
1/1/2017      1304
10/5/2014     1303
29/11/2014    1303
              ...
28/12/2014     762
5/1/2014       759
19/3/2018      759
18/4/2017      756
19/4/2017      754
26/12/2015     752
25/7/2018      752
31/3/2015      751
20/3/2017      750
26/3/2016      750
2/1/2014       747
19/11/2018     740
27/3/2016      738
2/1/2015       737
17/3/2014      735
28/12/2016     734
29/12/2015     733
30/12/2015     733
25/3/2016      731
21/3/2016      731
6/2/2017       729
30/12/2018     726
16/3/2015      726
31/12/2017     725
27/12/2018     723
5/2/2018       720
27/12/2016     720
4/1/2015       717
27/12/2015     687
3/1/2016       649
Name: fechaaccidente, Length: 1826, dtype: int64

In [29]:
accidentesnacional.dtypes

EDO                int64
MES                int64
ANIO               int64
MPIO               int64
HORA               int64
MINUTOS            int64
DIA                int64
DIASEMANA          int64
URBANA             int64
SUBURBANA          int64
TIPACCID           int64
AUTOMOVIL          int64
CAMPASAJ           int64
MICROBUS           int64
PASCAMION          int64
OMNIBUS            int64
TRANVIA            int64
CAMIONETA          int64
CAMION             int64
TRACTOR            int64
FERROCARRI         int64
MOTOCICLET         int64
BICICLETA          int64
OTROVEHIC          int64
CAUSAACCI          int64
CAPAROD            int64
SEXO               int64
ALIENTO            int64
CINTURON           int64
EDAD               int64
CONDMUERTO         int64
CONDHERIDO         int64
PASAMUERTO         int64
PASAHERIDO         int64
PEATMUERTO         int64
PEATHERIDO         int64
CICLMUERTO         int64
CICLHERIDO         int64
OTROMUERTO         int64
OTROHERIDO         int64
NEMUERTO           int64
NEHERIDO           int64
DIAs              object
MESs              object
ANIOs             object
fechaaccidente    object
dtype: object

In [30]:
accidentesnacional['fechaaccidentes'] = accidentesnacional['fechaaccidente'].astype(str)

In [31]:
feriadopranio = []
for row in accidentesnacional['fechaaccidentes']:
    if row =="1/1/2014":
        feriadopranio.append('Año nuevo 2014')
    elif row == "2/1/2014":
        feriadopranio.append('Vaciones fin de año 2014')
    elif row == "3/1/2014":
        feriadopranio.append('Vaciones fin de año 2014')
    elif row == "4/1/2014":
        feriadopranio.append('Vaciones fin de año 2014')
    elif row == "5/1/2014":
        feriadopranio.append('Vaciones fin de año 2014')
    elif row == "6/1/2014":
        feriadopranio.append('Vaciones fin de año 2014')
    elif row == "1/1/2015":
        feriadopranio.append('Año nuevo 2015')
    elif row == "2/1/2015":
        feriadopranio.append('Vaciones fin de año 2015')
    elif row == "3/1/2015":
        feriadopranio.append('Vaciones fin de año 2015')
    elif row == "4/1/2015":
        feriadopranio.append('Vaciones fin de año 2015')
    elif row == "5/1/2015":
        feriadopranio.append('Vaciones fin de año 2015')
    elif row == "6/1/2015":
        feriadopranio.append('Vaciones fin de año 2015')
    elif row == "1/1/2016":
        feriadopranio.append('Año nuevo 2016')
    elif row == "2/1/2016":
        feriadopranio.append('Vaciones fin de año 2016')
    elif row == "3/1/2016":
        feriadopranio.append('Vaciones fin de año 2016')
    elif row == "4/1/2016":
        feriadopranio.append('Vaciones fin de año 2016')
    elif row == "5/1/2016":
        feriadopranio.append('Vaciones fin de año 2016')
    elif row == "6/1/2016":
        feriadopranio.append('Vaciones fin de año 2016')
    elif row == "1/1/2017":
        feriadopranio.append('Año nuevo 2017')
    elif row == "2/1/2017":
        feriadopranio.append('Vaciones fin de año 2017')
    elif row == "3/1/2017":
        feriadopranio.append('Vaciones fin de año 2017')
    elif row == "4/1/2017":
        feriadopranio.append('Vaciones fin de año 2017')
    elif row == "5/1/2017":
        feriadopranio.append('Vaciones fin de año 2017')
    elif row == "6/1/2017":
        feriadopranio.append('Vaciones fin de año 2017')
    elif row == "1/1/2018":
        feriadopranio.append('Año nuevo 2018')
    elif row == "2/1/2018":
        feriadopranio.append('Vaciones fin de año 2018')
    elif row == "3/1/2018":
        feriadopranio.append('Vaciones fin de año 2018')
    elif row == "4/1/2018":
        feriadopranio.append('Vaciones fin de año 2018')
    elif row == "5/1/2018":
        feriadopranio.append('Vaciones fin de año 2018')
    elif row == "6/1/2018":
        feriadopranio.append('Vaciones fin de año 2018')
    elif row == "6/1/2018":
        feriadopranio.append('Vaciones fin de año 2018')
    elif row == "17/4/2014":
        feriadopranio.append('Semana Santa 2014')
    elif row == "18/4/2014":
        feriadopranio.append('Semana Santa 2014')
    elif row == "19/4/2014":
        feriadopranio.append('Semana Santa 2014')
    elif row == "20/4/2014":
        feriadopranio.append('Semana Santa 2014')
    elif row == "02/4/2015":
        feriadopranio.append('Semana Santa 2015')
    elif row == "03/4/2015":
        feriadopranio.append('Semana Santa 2015')
    elif row == "04/4/2015":
        feriadopranio.append('Semana Santa 2015')
    elif row == "05/4/2015":
        feriadopranio.append('Semana Santa 2015')
    elif row == "24/3/2016":
        feriadopranio.append('Semana Santa 2016')
    elif row == "25/3/2016":
        feriadopranio.append('Semana Santa 2016')
    elif row == "26/3/2016":
        feriadopranio.append('Semana Santa 2016')
    elif row == "27/3/2016":
        feriadopranio.append('Semana Santa 2016')
    elif row == "13/4/2017":
        feriadopranio.append('Semana Santa 2017')
    elif row == "14/4/2017":
        feriadopranio.append('Semana Santa 2017')
    elif row == "15/4/2017":
        feriadopranio.append('Semana Santa 2017')
    elif row == "16/4/2017":
        feriadopranio.append('Semana Santa 2017')
    elif row == "29/3/2018":
        feriadopranio.append('Semana Santa 2018')
    elif row == "30/3/2018":
        feriadopranio.append('Semana Santa 2018')
    elif row == "31/3/2018":
        feriadopranio.append('Semana Santa 2018')
    elif row == "1/4/2018":
        feriadopranio.append('Semana Santa 2018')
    elif row == "1/5/2014":
        feriadopranio.append('Dia del trabajo 2014')
    elif row == "1/5/2015":
        feriadopranio.append('Dia del trabajo 2015')
    elif row == "1/5/2016":
        feriadopranio.append('Dia del trabajo 2016')
    elif row == "1/5/2017":
        feriadopranio.append('Dia del trabajo 2017')
    elif row == "1/5/2018":
        feriadopranio.append('Dia del trabajo 2018')
    elif row == "5/5/2014":
        feriadopranio.append('Batalla de Puebla 2014')
    elif row == "5/5/2015":
        feriadopranio.append('Batalla de Puebla 2015')
    elif row == "5/5/2016":
        feriadopranio.append('Batalla de Puebla 2016')
    elif row == "5/5/2017":
        feriadopranio.append('Batalla de Puebla 2017')
    elif row == "5/5/2018":
        feriadopranio.append('Batalla de Puebla 2018')
    elif row == "15/9/2014":
        feriadopranio.append('Independencia de México 2014')
    elif row == "16/9/2014":
        feriadopranio.append('Independencia de México 2014')
    elif row == "15/9/2015":
        feriadopranio.append('Independencia de México 2015')
    elif row == "16/9/2015":
        feriadopranio.append('Independencia de México 2015')
    elif row == "15/9/2016":
        feriadopranio.append('Independencia de México 2016')
    elif row == "16/9/2016":
        feriadopranio.append('Independencia de México 2016')
    elif row == "15/9/2017":
        feriadopranio.append('Independencia de México 2017')
    elif row == "16/9/2017":
        feriadopranio.append('Independencia de México 2017')
    elif row == "15/9/2018":
        feriadopranio.append('Independencia de México 2018')
    elif row == "16/9/2018":
        feriadopranio.append('Independencia de México 2018')
    elif row == "15/7/2014":
        feriadopranio.append('Inicio vacaciones verano 2014')
    elif row == "18/8/2014":
        feriadopranio.append('Inicio clases verano 2014')
    elif row == "14/7/2015":
        feriadopranio.append('Inicio vacaciones verano 2015')
    elif row == "24/8/2015":
        feriadopranio.append('Inicio clases verano 2015')
    elif row == "15/7/2016":
        feriadopranio.append('Inicio vacaciones verano 2016')
    elif row == "22/8/2016":
        feriadopranio.append('Inicio clases verano 2016')
    elif row == "27/6/2017":
        feriadopranio.append('Inicio vacaciones verano 2017')
    elif row == "21/8/2017":
        feriadopranio.append('Inicio clases verano 2017')
    elif row == "25/6/2018":
        feriadopranio.append('Inicio vacaciones verano 2018')
    elif row == "20/8/2018":
        feriadopranio.append('Inicio clases verano 2018')
    elif row == "31/12/2014":
        feriadopranio.append('Fin de año 2014')
    elif row == "31/12/2015":
        feriadopranio.append('Fin de año 2015')
    elif row == "31/12/2016":
        feriadopranio.append('Fin de año 2016')
    elif row == "31/12/2017":
        feriadopranio.append('Fin de año 2017')
    elif row == "31/12/2018":
        feriadopranio.append('Fin de año 2018')
    elif row == "22/12/2014":
        feriadopranio.append('Vacaciones fin de año 2014')
    elif row == "23/12/2014":
        feriadopranio.append('Vacaciones fin de año 2014')
    elif row == "24/12/2014":
        feriadopranio.append('Nochebuena 2014')
    elif row == "25/12/2014":
        feriadopranio.append('Navidad 2014')
    elif row == "26/12/2014":
        feriadopranio.append('Vacaciones fin de año 2014')
    elif row == "27/12/2014":
        feriadopranio.append('Vacaciones fin de año 2014')
    elif row == "28/12/2014":
        feriadopranio.append('Vacaciones fin de año 2014')
    elif row == "29/12/2014":
        feriadopranio.append('Vacaciones fin de año 2014')
    elif row == "30/12/2014":
        feriadopranio.append('Vacaciones fin de año 2014')
    elif row == "22/12/2015":
        feriadopranio.append('Vacaciones fin de año 2015')
    elif row == "23/12/2015":
        feriadopranio.append('Vacaciones fin de año 2015')
    elif row == "24/12/2015":
        feriadopranio.append('Nochebuena 2015')
    elif row == "25/12/2015":
        feriadopranio.append('Navidad 2015')
    elif row == "26/12/2015":
        feriadopranio.append('Vacaciones fin de año 2015')
    elif row == "27/12/2015":
        feriadopranio.append('Vacaciones fin de año 2015')
    elif row == "28/12/2015":
        feriadopranio.append('Vacaciones fin de año 2015')
    elif row == "29/12/2015":
        feriadopranio.append('Vacaciones fin de año 2015')
    elif row == "30/12/2015":
        feriadopranio.append('Vacaciones fin de año 2015')
    elif row == "19/12/2016":
        feriadopranio.append('Vacaciones fin de año 2016')
    elif row == "20/12/2016":
        feriadopranio.append('Vacaciones fin de año 2016')
    elif row == "21/12/2016":
        feriadopranio.append('Vacaciones fin de año 2016')
    elif row == "22/12/2016":
        feriadopranio.append('Vacaciones fin de año 2016')
    elif row == "23/12/2016":
        feriadopranio.append('Vacaciones fin de año 2016')
    elif row == "24/12/2016":
        feriadopranio.append('Nochebuena 2016')
    elif row == "25/12/2016":
        feriadopranio.append('Navidad 2016')
    elif row == "26/12/2016":
        feriadopranio.append('Vacaciones fin de año 2016')
    elif row == "27/12/2016":
        feriadopranio.append('Vacaciones fin de año 2016')
    elif row == "28/12/2016":
        feriadopranio.append('Vacaciones fin de año 2016')
    elif row == "29/12/2016":
        feriadopranio.append('Vacaciones fin de año 2016')
    elif row == "30/12/2016":
        feriadopranio.append('Vacaciones fin de año 2016')
    elif row == "21/12/2017":
        feriadopranio.append('Vacaciones fin de año 2017')
    elif row == "22/12/2017":
        feriadopranio.append('Vacaciones fin de año 2017')
    elif row == "23/12/2017":
        feriadopranio.append('Vacaciones fin de año 2017')
    elif row == "24/12/2017":
        feriadopranio.append('Nochebuena 2017')
    elif row == "25/12/2017":
        feriadopranio.append('Navidad 2017')
    elif row == "26/12/2017":
        feriadopranio.append('Vacaciones fin de año 2017')
    elif row == "27/12/2017":
        feriadopranio.append('Vacaciones fin de año 2017')
    elif row == "28/12/2017":
        feriadopranio.append('Vacaciones fin de año 2017')
    elif row == "29/12/2017":
        feriadopranio.append('Vacaciones fin de año 2017')
    elif row == "30/12/2017":
        feriadopranio.append('Vacaciones fin de año 2017')
    elif row == "20/12/2018":
        feriadopranio.append('Vacaciones fin de año 2018')
    elif row == "21/12/2018":
        feriadopranio.append('Vacaciones fin de año 2018')
    elif row == "22/12/2018":
        feriadopranio.append('Vacaciones fin de año 2018')
    elif row == "23/12/2018":
        feriadopranio.append('Vacaciones fin de año 2018')
    elif row == "24/12/2018":
        feriadopranio.append('Nochebuena 2018')
    elif row == "25/12/2018":
        feriadopranio.append('Navidad 2018')
    elif row == "26/12/2018":
        feriadopranio.append('Vacaciones fin de año 2018')
    elif row == "27/12/2018":
        feriadopranio.append('Vacaciones fin de año 2018')
    elif row == "28/12/2018":
        feriadopranio.append('Vacaciones fin de año 2018')
    elif row == "29/12/2018":
        feriadopranio.append('Vacaciones fin de año 2018')
    elif row == "30/12/2018":
        feriadopranio.append('Vacaciones fin de año 2018')
    else:
        feriadopranio.append('No feriado')

In [32]:
accidentesnacional['feriadopranio'] = feriadopranio

In [33]:
accidentesnacional.head()

,EDO,MES,ANIO,MPIO,HORA,MINUTOS,DIA,DIASEMANA,URBANA,SUBURBANA,...,OTROMUERTO,OTROHERIDO,NEMUERTO,NEHERIDO,DIAs,MESs,ANIOs,fechaaccidente,fechaaccidentes,feriadopranio
0,1,1,2014,5,20,30,2,4,0,2,...,0,0,0,0,2,1,2014,2/1/2014,2/1/2014,Vaciones fin de año 2014
1,1,1,2014,5,9,15,3,5,1,0,...,0,0,0,0,3,1,2014,3/1/2014,3/1/2014,Vaciones fin de año 2014
2,1,1,2014,5,9,0,3,5,1,0,...,0,0,0,0,3,1,2014,3/1/2014,3/1/2014,Vaciones fin de año 2014
3,1,1,2014,5,9,0,3,5,1,0,...,0,0,0,0,3,1,2014,3/1/2014,3/1/2014,Vaciones fin de año 2014
4,1,1,2014,5,23,20,5,7,2,0,...,0,0,0,0,5,1,2014,5/1/2014,5/1/2014,Vaciones fin de año 2014

In [34]:
accidentesnacional['feriadopranio'].value_counts()

No feriado                       1732037
Vacaciones fin de año 2016          9040
Vacaciones fin de año 2018          8464
Vacaciones fin de año 2017          7478
Vacaciones fin de año 2014          6273
Vacaciones fin de año 2015          5785
Vaciones fin de año 2017            4130
Vaciones fin de año 2014            4043
Vaciones fin de año 2018            4021
Vaciones fin de año 2015            3898
Vaciones fin de año 2016            3844
Semana Santa 2014                   3433
Semana Santa 2018                   3424
Semana Santa 2017                   3135
Semana Santa 2016                   3074
Independencia de México 2017        2280
Independencia de México 2018        2095
Independencia de México 2016        2051
Independencia de México 2015        1919
Independencia de México 2014        1756
Año nuevo 2018                      1305
Año nuevo 2017                      1304
Año nuevo 2016                      1285
Año nuevo 2014                      1264
Dia del trabajo 2016                1206
Año nuevo 2015                      1165
Batalla de Puebla 2018              1145
Dia del trabajo 2015                1137
Batalla de Puebla 2015              1132
Nochebuena 2015                     1085
Inicio clases verano 2014           1070
Inicio vacaciones verano 2016       1054
Nochebuena 2016                     1041
Nochebuena 2014                     1018
Nochebuena 2017                     1008
Inicio clases verano 2018           1000
Inicio clases verano 2015            992
Navidad 2015                         985
Dia del trabajo 2017                 976
Inicio vacaciones verano 2014        975
Inicio clases verano 2017            973
Batalla de Puebla 2014               973
Inicio vacaciones verano 2015        965
Inicio clases verano 2016            960
Navidad 2016                         949
Inicio vacaciones verano 2018        946
Batalla de Puebla 2017               941
Navidad 2014                         927
Fin de año 2015                      917
Nochebuena 2018                      913
Dia del trabajo 2014                 908
Batalla de Puebla 2016               895
Dia del trabajo 2018                 880
Fin de año 2014                      866
Fin de año 2016                      848
Inicio vacaciones verano 2017        837
Navidad 2017                         829
Fin de año 2018                      818
Navidad 2018                         786
Fin de año 2017                      725
Name: feriadopranio, dtype: int64

In [35]:
accidentesnacional.groupby(feriadopranio)['DIASEMANA'].value_counts()

                              DIASEMANA
Año nuevo 2014                3            1264
Año nuevo 2015                4            1165
Año nuevo 2016                5            1285
Año nuevo 2017                7            1304
Año nuevo 2018                1            1305
Batalla de Puebla 2014        1             973
Batalla de Puebla 2015        2            1132
Batalla de Puebla 2016        4             895
Batalla de Puebla 2017        5             941
Batalla de Puebla 2018        6            1145
Dia del trabajo 2014          4             908
Dia del trabajo 2015          5            1137
Dia del trabajo 2016          7            1206
Dia del trabajo 2017          1             976
Dia del trabajo 2018          2             880
Fin de año 2014               3             866
Fin de año 2015               4             917
Fin de año 2016               6             848
Fin de año 2017               7             725
Fin de año 2018               1             818
Independencia de México 2014  1             981
                              2             775
Independencia de México 2015  2            1076
                              3             843
Independencia de México 2016  4            1123
                              5             928
Independencia de México 2017  5            1191
                              6            1089
Independencia de México 2018  6            1069
                              7            1026
                                           ...
Vacaciones fin de año 2018    6            2114
                              5            1990
                              4            1783
                              7            1748
                              3             829
Vaciones fin de año 2014      6             860
                              5             849
                              1             828
                              7             759
                              4             747
Vaciones fin de año 2015      2             877
                              1             789
                              6             778
                              5             737
                              7             717
Vaciones fin de año 2016      3             814
                              2             809
                              1             807
                              6             765
                              7             649
Vaciones fin de año 2017      5             890
                              1             837
                              3             823
                              4             794
                              2             786
Vaciones fin de año 2018      6             901
                              5             802
                              3             776
                              2             775
                              4             767
Name: DIASEMANA, Length: 123, dtype: int64

In [36]:
feriadodummy = []
for row in accidentesnacional['feriadopranio']:
    if row =="No feriado":
        feriadodummy.append('No feriado')
    else:
        feriadodummy.append('Feriado')

In [37]:
#print(feriadodummy)

In [38]:
accidentesnacional['Feriadodummy'] = feriadodummy

In [39]:
feriadotipo = []
for row in accidentesnacional['fechaaccidentes']:
    if row =="1/1/2014":
        feriadotipo.append('Año nuevo')
    elif row == "2/1/2014":
        feriadotipo.append('Vaciones fin de año')
    elif row == "3/1/2014":
        feriadotipo.append('Vaciones fin de año')
    elif row == "4/1/2014":
        feriadotipo.append('Vaciones fin de año')
    elif row == "5/1/2014":
        feriadotipo.append('Vaciones fin de año')
    elif row == "6/1/2014":
        feriadotipo.append('Vaciones fin de año')
    elif row == "1/1/2015":
        feriadotipo.append('Año nuevo')
    elif row == "2/1/2015":
        feriadotipo.append('Vaciones fin de año')
    elif row == "3/1/2015":
        feriadotipo.append('Vaciones fin de año')
    elif row == "4/1/2015":
        feriadotipo.append('Vaciones fin de año')
    elif row == "5/1/2015":
        feriadotipo.append('Vaciones fin de año')
    elif row == "6/1/2015":
        feriadotipo.append('Vaciones fin de año')
    elif row == "1/1/2016":
        feriadotipo.append('Año nuevo')
    elif row == "2/1/2016":
        feriadotipo.append('Vaciones fin de año')
    elif row == "3/1/2016":
        feriadotipo.append('Vaciones fin de año')
    elif row == "4/1/2016":
        feriadotipo.append('Vaciones fin de año')
    elif row == "5/1/2016":
        feriadotipo.append('Vaciones fin de año')
    elif row == "6/1/2016":
        feriadotipo.append('Vaciones fin de año')
    elif row == "1/1/2017":
        feriadotipo.append('Año nuevo')
    elif row == "2/1/2017":
        feriadotipo.append('Vaciones fin de año')
    elif row == "3/1/2017":
        feriadotipo.append('Vaciones fin de año')
    elif row == "4/1/2017":
        feriadotipo.append('Vaciones fin de año')
    elif row == "5/1/2017":
        feriadotipo.append('Vaciones fin de año')
    elif row == "6/1/2017":
        feriadotipo.append('Vaciones fin de año')
    elif row == "1/1/2018":
        feriadotipo.append('Año nuevo')
    elif row == "2/1/2018":
        feriadotipo.append('Vaciones fin de año')
    elif row == "3/1/2018":
        feriadotipo.append('Vaciones fin de año')
    elif row == "4/1/2018":
        feriadotipo.append('Vaciones fin de año')
    elif row == "5/1/2018":
        feriadotipo.append('Vaciones fin de año')
    elif row == "6/1/2018":
        feriadotipo.append('Vaciones fin de año')
    elif row == "6/1/2018":
        feriadotipo.append('Vaciones fin de año')
    elif row == "17/4/2014":
        feriadotipo.append('Semana Santa')
    elif row == "18/4/2014":
        feriadotipo.append('Semana Santa')
    elif row == "19/4/2014":
        feriadotipo.append('Semana Santa')
    elif row == "20/4/2014":
        feriadotipo.append('Semana Santa')
    elif row == "02/4/2015":
        feriadotipo.append('Semana Santa')
    elif row == "03/4/2015":
        feriadotipo.append('Semana Santa')
    elif row == "04/4/2015":
        feriadotipo.append('Semana Santa')
    elif row == "05/4/2015":
        feriadotipo.append('Semana Santa')
    elif row == "24/3/2016":
        feriadotipo.append('Semana Santa')
    elif row == "25/3/2016":
        feriadotipo.append('Semana Santa')
    elif row == "26/3/2016":
        feriadotipo.append('Semana Santa')
    elif row == "27/3/2016":
        feriadotipo.append('Semana Santa')
    elif row == "13/4/2017":
        feriadotipo.append('Semana Santa')
    elif row == "14/4/2017":
        feriadotipo.append('Semana Santa')
    elif row == "15/4/2017":
        feriadotipo.append('Semana Santa')
    elif row == "16/4/2017":
        feriadotipo.append('Semana Santa')
    elif row == "29/3/2018":
        feriadotipo.append('Semana Santa')
    elif row == "30/3/2018":
        feriadotipo.append('Semana Santa')
    elif row == "31/3/2018":
        feriadotipo.append('Semana Santa')
    elif row == "1/4/2018":
        feriadotipo.append('Semana Santa')
    elif row == "1/5/2014":
        feriadotipo.append('Dia del trabajo')
    elif row == "1/5/2015":
        feriadotipo.append('Dia del trabajo')
    elif row == "1/5/2016":
        feriadotipo.append('Dia del trabajo')
    elif row == "1/5/2017":
        feriadotipo.append('Dia del trabajo')
    elif row == "1/5/2018":
        feriadotipo.append('Dia del trabajo')
    elif row == "5/5/2014":
        feriadotipo.append('Dia del trabajo')
    elif row == "5/5/2015":
        feriadotipo.append('Batalla de Puebla')
    elif row == "5/5/2016":
        feriadotipo.append('Batalla de Puebla')
    elif row == "5/5/2017":
        feriadotipo.append('Batalla de Puebla')
    elif row == "5/5/2018":
        feriadotipo.append('Batalla de Puebla')
    elif row == "15/9/2014":
        feriadotipo.append('Independencia de México')
    elif row == "16/9/2014":
        feriadotipo.append('Independencia de México')
    elif row == "15/9/2015":
        feriadotipo.append('Independencia de México')
    elif row == "16/9/2015":
        feriadotipo.append('Independencia de México')
    elif row == "15/9/2016":
        feriadotipo.append('Independencia de México')
    elif row == "16/9/2016":
        feriadotipo.append('Independencia de México')
    elif row == "15/9/2017":
        feriadotipo.append('Independencia de México')
    elif row == "16/9/2017":
        feriadotipo.append('Independencia de México')
    elif row == "15/9/2018":
        feriadotipo.append('Independencia de México')
    elif row == "16/9/2018":
        feriadotipo.append('Independencia de México')
    elif row == "15/7/2014":
        feriadotipo.append('Inicio vacaciones verano')
    elif row == "18/8/2014":
        feriadotipo.append('Inicio clases verano')
    elif row == "14/7/2015":
        feriadotipo.append('Inicio vacaciones verano')
    elif row == "24/8/2015":
        feriadotipo.append('Inicio clases verano')
    elif row == "15/7/2016":
        feriadotipo.append('Inicio vacaciones verano')
    elif row == "22/8/2016":
        feriadotipo.append('Inicio clases verano')
    elif row == "27/6/2017":
        feriadotipo.append('Inicio vacaciones verano')
    elif row == "21/8/2017":
        feriadotipo.append('Inicio clases verano')
    elif row == "25/6/2018":
        feriadotipo.append('Inicio vacaciones verano')
    elif row == "20/8/2018":
        feriadotipo.append('Inicio clases verano')
    elif row == "31/12/2014":
        feriadotipo.append('Fin de año')
    elif row == "31/12/2015":
        feriadotipo.append('Fin de año')
    elif row == "31/12/2016":
        feriadotipo.append('Fin de año')
    elif row == "31/12/2017":
        feriadotipo.append('Fin de año')
    elif row == "31/12/2018":
        feriadotipo.append('Fin de año')
    elif row == "22/12/2014":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "23/12/2014":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "24/12/2014":
        feriadotipo.append('Nochebuena')
    elif row == "25/12/2014":
        feriadotipo.append('Navidad')
    elif row == "26/12/2014":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "27/12/2014":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "28/12/2014":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "29/12/2014":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "30/12/2014":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "22/12/2015":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "23/12/2015":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "24/12/2015":
        feriadotipo.append('Nochebuena')
    elif row == "25/12/2015":
        feriadotipo.append('Navidad')
    elif row == "26/12/2015":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "27/12/2015":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "28/12/2015":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "29/12/2015":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "30/12/2015":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "19/12/2016":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "20/12/2016":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "21/12/2016":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "22/12/2016":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "23/12/2016":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "24/12/2016":
        feriadotipo.append('Nochebuena')
    elif row == "25/12/2016":
        feriadotipo.append('Navidad')
    elif row == "26/12/2016":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "27/12/2016":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "28/12/2016":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "29/12/2016":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "30/12/2016":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "21/12/2017":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "22/12/2017":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "23/12/2017":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "24/12/2017":
        feriadotipo.append('Nochebuena')
    elif row == "25/12/2017":
        feriadotipo.append('Navidad')
    elif row == "26/12/2017":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "27/12/2017":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "28/12/2017":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "29/12/2017":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "30/12/2017":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "20/12/2018":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "21/12/2018":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "22/12/2018":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "23/12/2018":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "24/12/2018":
        feriadotipo.append('Nochebuena')
    elif row == "25/12/2018":
        feriadotipo.append('Navidad')
    elif row == "26/12/2018":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "27/12/2018":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "28/12/2018":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "29/12/2018":
        feriadotipo.append('Vacaciones fin de año')
    elif row == "30/12/2018":
        feriadotipo.append('Vacaciones fin de año')
    else:
        feriadotipo.append('No feriado')

In [40]:
#print(feriadotipo)

In [41]:
accidentesnacional['Feriadotipo'] = feriadotipo

In [42]:
accidentesnacional.head()

,EDO,MES,ANIO,MPIO,HORA,MINUTOS,DIA,DIASEMANA,URBANA,SUBURBANA,...,NEMUERTO,NEHERIDO,DIAs,MESs,ANIOs,fechaaccidente,fechaaccidentes,feriadopranio,Feriadodummy,Feriadotipo
0,1,1,2014,5,20,30,2,4,0,2,...,0,0,2,1,2014,2/1/2014,2/1/2014,Vaciones fin de año 2014,Feriado,Vaciones fin de año
1,1,1,2014,5,9,15,3,5,1,0,...,0,0,3,1,2014,3/1/2014,3/1/2014,Vaciones fin de año 2014,Feriado,Vaciones fin de año
2,1,1,2014,5,9,0,3,5,1,0,...,0,0,3,1,2014,3/1/2014,3/1/2014,Vaciones fin de año 2014,Feriado,Vaciones fin de año
3,1,1,2014,5,9,0,3,5,1,0,...,0,0,3,1,2014,3/1/2014,3/1/2014,Vaciones fin de año 2014,Feriado,Vaciones fin de año
4,1,1,2014,5,23,20,5,7,2,0,...,0,0,5,1,2014,5/1/2014,5/1/2014,Vaciones fin de año 2014,Feriado,Vaciones fin de año

In [43]:
accidentesnacional.count()

EDO                1852183
MES                1852183
ANIO               1852183
MPIO               1852183
HORA               1852183
MINUTOS            1852183
DIA                1852183
DIASEMANA          1852183
URBANA             1852183
SUBURBANA          1852183
TIPACCID           1852183
AUTOMOVIL          1852183
CAMPASAJ           1852183
MICROBUS           1852183
PASCAMION          1852183
OMNIBUS            1852183
TRANVIA            1852183
CAMIONETA          1852183
CAMION             1852183
TRACTOR            1852183
FERROCARRI         1852183
MOTOCICLET         1852183
BICICLETA          1852183
OTROVEHIC          1852183
CAUSAACCI          1852183
CAPAROD            1852183
SEXO               1852183
ALIENTO            1852183
CINTURON           1852183
EDAD               1852183
CONDMUERTO         1852183
CONDHERIDO         1852183
PASAMUERTO         1852183
PASAHERIDO         1852183
PEATMUERTO         1852183
PEATHERIDO         1852183
CICLMUERTO         1852183
CICLHERIDO         1852183
OTROMUERTO         1852183
OTROHERIDO         1852183
NEMUERTO           1852183
NEHERIDO           1852183
DIAs               1852183
MESs               1852183
ANIOs              1852183
fechaaccidente     1852183
fechaaccidentes    1852183
feriadopranio      1852183
Feriadodummy       1852183
Feriadotipo        1852183
dtype: int64

In [44]:
accidentesnacional['feriadopranio'].value_counts()

No feriado                       1732037
Vacaciones fin de año 2016          9040
Vacaciones fin de año 2018          8464
Vacaciones fin de año 2017          7478
Vacaciones fin de año 2014          6273
Vacaciones fin de año 2015          5785
Vaciones fin de año 2017            4130
Vaciones fin de año 2014            4043
Vaciones fin de año 2018            4021
Vaciones fin de año 2015            3898
Vaciones fin de año 2016            3844
Semana Santa 2014                   3433
Semana Santa 2018                   3424
Semana Santa 2017                   3135
Semana Santa 2016                   3074
Independencia de México 2017        2280
Independencia de México 2018        2095
Independencia de México 2016        2051
Independencia de México 2015        1919
Independencia de México 2014        1756
Año nuevo 2018                      1305
Año nuevo 2017                      1304
Año nuevo 2016                      1285
Año nuevo 2014                      1264
Dia del trabajo 2016                1206
Año nuevo 2015                      1165
Batalla de Puebla 2018              1145
Dia del trabajo 2015                1137
Batalla de Puebla 2015              1132
Nochebuena 2015                     1085
Inicio clases verano 2014           1070
Inicio vacaciones verano 2016       1054
Nochebuena 2016                     1041
Nochebuena 2014                     1018
Nochebuena 2017                     1008
Inicio clases verano 2018           1000
Inicio clases verano 2015            992
Navidad 2015                         985
Dia del trabajo 2017                 976
Inicio vacaciones verano 2014        975
Inicio clases verano 2017            973
Batalla de Puebla 2014               973
Inicio vacaciones verano 2015        965
Inicio clases verano 2016            960
Navidad 2016                         949
Inicio vacaciones verano 2018        946
Batalla de Puebla 2017               941
Navidad 2014                         927
Fin de año 2015                      917
Nochebuena 2018                      913
Dia del trabajo 2014                 908
Batalla de Puebla 2016               895
Dia del trabajo 2018                 880
Fin de año 2014                      866
Fin de año 2016                      848
Inicio vacaciones verano 2017        837
Navidad 2017                         829
Fin de año 2018                      818
Navidad 2018                         786
Fin de año 2017                      725
Name: feriadopranio, dtype: int64

In [45]:
accidentesnacional['Feriadodummy'].value_counts()

No feriado    1732037
Feriado        120146
Name: Feriadodummy, dtype: int64

In [46]:
accidentesnacional['Feriadotipo'].value_counts()

No feriado                  1732037
Vacaciones fin de año         37040
Vaciones fin de año           19936
Semana Santa                  13066
Independencia de México       10101
Año nuevo                      6323
Dia del trabajo                6080
Nochebuena                     5065
Inicio clases verano           4995
Inicio vacaciones verano       4777
Navidad                        4476
Fin de año                     4174
Batalla de Puebla              4113
Name: Feriadotipo, dtype: int64

In [47]:
accidentesnacional.to_csv('accidentesnacionalVF.csv')

In [49]:
accidentesnacional["EDO"].value_counts()

19    401592
14    168084
8     147376
11     95051
2      75724
5      72934
26     69574
22     68235
28     67203
15     63435
9      62077
16     60738
21     47038
17     45896
30     44778
25     42586
23     32629
6      29579
31     28905
10     28658
24     23827
1      20163
20     19624
3      19062
12     18808
4      18101
13     17416
29     14779
27     13210
7      12972
32     12437
18      9692
Name: EDO, dtype: int64

In [52]:
accidentesnacional.groupby("EDO")["MPIO"].value_counts()

EDO  MPIO
1    1       14497
     5        3288
     7         716
     3         496
     11        336
     2         282
     6         197
     10        132
     9          94
     4          66
     8          59
2    4       39620
     1       18286
     2        9405
     5        7466
     3         947
3    3       10634
     8        4654
     1        2472
     2         887
     9         415
4    3        9458
     2        4446
     4        1126
     9        1034
     1         700
     11        440
     6         265
     8         259
     10        243
             ...
31   73          1
32   56       3817
     10       2722
     17       2553
     39        575
     42        350
     5         320
     55        243
     34        230
     20        219
     48        188
     24        179
     49        161
     29        145
     36        136
     38        132
     7         124
     51        109
     22         75
     52         66
     19         38
     40         14
     23         12
     8           9
     31          6
     32          4
     57          4
     45          3
     44          2
     25          1
Name: MPIO, Length: 1812, dtype: int64

In [115]:
clavesedo=pd.read_csv("Estados_Inegi.csv")

In [116]:
clavesedo.head()

  cve_ent EDO               nom_ent
0     a01  a1        Aguascalientes
1     a02  a2       Baja California
2     a03  a3   Baja California Sur
3     a04  a4              Campeche
4     a05  a5  Coahuila de Zaragoza

In [99]:
import numpy as np

In [117]:
clavesedo.dtypes

cve_ent    object
EDO        object
nom_ent    object
dtype: object

In [118]:
clavesedo["cve_ent"]=clavesedo["cve_ent"].astype(str)
clavesedo["EDO"]=clavesedo["EDO"].astype(str)

In [119]:
clavesedo["cve_ent"] = clavesedo["cve_ent"].str[1:]
clavesedo["EDO"] = clavesedo["EDO"].str[1:]

In [120]:
clavesedo

   cve_ent EDO                          nom_ent
0       01   1                   Aguascalientes
1       02   2                  Baja California
2       03   3              Baja California Sur
3       04   4                         Campeche
4       05   5             Coahuila de Zaragoza
5       06   6                           Colima
6       07   7                          Chiapas
7       08   8                        Chihuahua
8       09   9                 Ciudad de México
9       10  10                          Durango
10      11  11                       Guanajuato
11      12  12                         Guerrero
12      13  13                          Hidalgo
13      14  14                          Jalisco
14      15  15                           México
15      16  16              Michoacán de Ocampo
16      17  17                          Morelos
17      18  18                          Nayarit
18      19  19                       Nuevo León
19      20  20                           Oaxaca
20      21  21                           Puebla
21      22  22                        Querétaro
22      23  23                     Quintana Roo
23      24  24                  San Luis Potosí
24      25  25                          Sinaloa
25      26  26                           Sonora
26      27  27                          Tabasco
27      28  28                       Tamaulipas
28      29  29                         Tlaxcala
29      30  30  Veracruz de Ignacio de la Llave
30      31  31                          Yucatán
31      32  32                        Zacatecas
32      an  an                              NaN

In [121]:
clavesedo.dtypes

cve_ent    object
EDO        object
nom_ent    object
dtype: object

In [122]:
clavesedo = clavesedo.dropna(how='any')

In [124]:
clavesedo

   cve_ent EDO                          nom_ent
0       01   1                   Aguascalientes
1       02   2                  Baja California
2       03   3              Baja California Sur
3       04   4                         Campeche
4       05   5             Coahuila de Zaragoza
5       06   6                           Colima
6       07   7                          Chiapas
7       08   8                        Chihuahua
8       09   9                 Ciudad de México
9       10  10                          Durango
10      11  11                       Guanajuato
11      12  12                         Guerrero
12      13  13                          Hidalgo
13      14  14                          Jalisco
14      15  15                           México
15      16  16              Michoacán de Ocampo
16      17  17                          Morelos
17      18  18                          Nayarit
18      19  19                       Nuevo León
19      20  20                           Oaxaca
20      21  21                           Puebla
21      22  22                        Querétaro
22      23  23                     Quintana Roo
23      24  24                  San Luis Potosí
24      25  25                          Sinaloa
25      26  26                           Sonora
26      27  27                          Tabasco
27      28  28                       Tamaulipas
28      29  29                         Tlaxcala
29      30  30  Veracruz de Ignacio de la Llave
30      31  31                          Yucatán
31      32  32                        Zacatecas

In [125]:
cvemun=pd.read_csv("Cve mun INEGI.csv")

In [126]:
cvemun

,EDO,cve_ent,nom_ent,MPIO,cve_mun,nom_mun,CVE_MUN_COMP
0,a1,a01,Aguascalientes,a1,a001,Aguascalientes,a01001
1,a1,a01,Aguascalientes,a2,a002,Asientos,a01002
2,a1,a01,Aguascalientes,a3,a003,Calvillo,a01003
3,a1,a01,Aguascalientes,a4,a004,Cosío,a01004
4,a1,a01,Aguascalientes,a5,a005,Jesús María,a01005
5,a1,a01,Aguascalientes,a6,a006,Pabellón de Arteaga,a01006
6,a1,a01,Aguascalientes,a7,a007,Rincón de Romos,a01007
7,a1,a01,Aguascalientes,a8,a008,San José de Gracia,a01008
8,a1,a01,Aguascalientes,a9,a009,Tepezalá,a01009
9,a1,a01,Aguascalientes,a10,a010,El Llano,a01010
10,a1,a01,Aguascalientes,a11,a011,San Francisco de los Romo,a01011
11,a2,a02,Baja California,a1,a001,Ensenada,a02001
12,a2,a02,Baja California,a2,a002,Mexicali,a02002
13,a2,a02,Baja California,a3,a003,Tecate,a02003
14,a2,a02,Baja California,a4,a004,Tijuana,a02004
15,a2,a02,Baja California,a5,a005,Playas de Rosarito,a02005
16,a3,a03,Baja California Sur,a1,a001,Comondú,a03001
17,a3,a03,Baja California Sur,a2,a002,Mulegé,a03002
18,a3,a03,Baja California Sur,a3,a003,La Paz,a03003
19,a3,a03,Baja California Sur,a8,a008,Los Cabos,a03008
20,a3,a03,Baja California Sur,a9,a009,Loreto,a03009
21,a4,a04,Campeche,a1,a001,Calkiní,a04001
22,a4,a04,Campeche,a2,a002,Campeche,a04002
23,a4,a04,Campeche,a3,a003,Carmen,a04003
24,a4,a04,Campeche,a4,a004,Champotón,a04004
25,a4,a04,Campeche,a5,a005,Hecelchakán,a04005
26,a4,a04,Campeche,a6,a006,Hopelchén,a04006
27,a4,a04,Campeche,a7,a007,Palizada,a04007
28,a4,a04,Campeche,a8,a008,Tenabo,a04008
29,a4,a04,Campeche,a9,a009,Escárcega,a04009
...,...,...,...,...,...,...,...
2425,a32,a32,Zacatecas,a30,a030,Momax,a32030
2426,a32,a32,Zacatecas,a31,a031,Monte Escobedo,a32031
2427,a32,a32,Zacatecas,a32,a032,Morelos,a32032
2428,a32,a32,Zacatecas,a33,a033,Moyahua de Estrada,a32033
2429,a32,a32,Zacatecas,a34,a034,Nochistlán de Mejía,a32034
2430,a32,a32,Zacatecas,a35,a035,Noria de Ángeles,a32035
2431,a32,a32,Zacatecas,a36,a036,Ojocaliente,a32036
2432,a32,a32,Zacatecas,a37,a037,Pánuco,a32037
2433,a32,a32,Zacatecas,a38,a038,Pinos,a32038
2434,a32,a32,Zacatecas,a39,a039,Río Grande,a32039
2435,a32,a32,Zacatecas,a40,a040,Sain Alto,a32040
2436,a32,a32,Zacatecas,a41,a041,El Salvador,a32041
2437,a32,a32,Zacatecas,a42,a042,Sombrerete,a32042
2438,a32,a32,Zacatecas,a43,a043,Susticacán,a32043
2439,a32,a32,Zacatecas,a44,a044,Tabasco,a32044
2440,a32,a32,Zacatecas,a45,a045,Tepechitlán,a32045
2441,a32,a32,Zacatecas,a46,a046,Tepetongo,a32046
2442,a32,a32,Zacatecas,a47,a047,Teúl de González Ortega,a32047
2443,a32,a32,Zacatecas,a48,a048,Tlaltenango de Sánchez Román,a32048
2444,a32,a32,Zacatecas,a49,a049,Valparaíso,a32049
2445,a32,a32,Zacatecas,a50,a050,Vetagrande,a32050
2446,a32,a32,Zacatecas,a51,a051,Villa de Cos,a32051
2447,a32,a32,Zacatecas,a52,a052,Villa García,a32052
2448,a32,a32,Zacatecas,a53,a053,Villa González Ortega,a32053
2449,a32,a32,Zacatecas,a54,a054,Villa Hidalgo,a32054
2450,a32,a32,Zacatecas,a55,a055,Villanueva,a32055
2451,a32,a32,Zacatecas,a56,a056,Zacatecas,a32056
2452,a32,a32,Zacatecas,a57,a057,Trancoso,a32057
2453,a32,a32,Zacatecas,a58,a058,Santa María de la Paz,a32058
2454,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [127]:
cvemun["EDO"] = cvemun["EDO"].str[1:]
cvemun["cve_ent"] = cvemun["cve_ent"].str[1:]
cvemun["cve_mun"] = cvemun["cve_mun"].str[1:]
cvemun["CVE_MUN_COMP"] = cvemun["CVE_MUN_COMP"].str[1:]
cvemun["MPIO"] = cvemun["MPIO"].str[1:]

In [128]:
cvemun

,EDO,cve_ent,nom_ent,MPIO,cve_mun,nom_mun,CVE_MUN_COMP
0,1,01,Aguascalientes,1,001,Aguascalientes,01001
1,1,01,Aguascalientes,2,002,Asientos,01002
2,1,01,Aguascalientes,3,003,Calvillo,01003
3,1,01,Aguascalientes,4,004,Cosío,01004
4,1,01,Aguascalientes,5,005,Jesús María,01005
5,1,01,Aguascalientes,6,006,Pabellón de Arteaga,01006
6,1,01,Aguascalientes,7,007,Rincón de Romos,01007
7,1,01,Aguascalientes,8,008,San José de Gracia,01008
8,1,01,Aguascalientes,9,009,Tepezalá,01009
9,1,01,Aguascalientes,10,010,El Llano,01010
10,1,01,Aguascalientes,11,011,San Francisco de los Romo,01011
11,2,02,Baja California,1,001,Ensenada,02001
12,2,02,Baja California,2,002,Mexicali,02002
13,2,02,Baja California,3,003,Tecate,02003
14,2,02,Baja California,4,004,Tijuana,02004
15,2,02,Baja California,5,005,Playas de Rosarito,02005
16,3,03,Baja California Sur,1,001,Comondú,03001
17,3,03,Baja California Sur,2,002,Mulegé,03002
18,3,03,Baja California Sur,3,003,La Paz,03003
19,3,03,Baja California Sur,8,008,Los Cabos,03008
20,3,03,Baja California Sur,9,009,Loreto,03009
21,4,04,Campeche,1,001,Calkiní,04001
22,4,04,Campeche,2,002,Campeche,04002
23,4,04,Campeche,3,003,Carmen,04003
24,4,04,Campeche,4,004,Champotón,04004
25,4,04,Campeche,5,005,Hecelchakán,04005
26,4,04,Campeche,6,006,Hopelchén,04006
27,4,04,Campeche,7,007,Palizada,04007
28,4,04,Campeche,8,008,Tenabo,04008
29,4,04,Campeche,9,009,Escárcega,04009
...,...,...,...,...,...,...,...
2425,32,32,Zacatecas,30,030,Momax,32030
2426,32,32,Zacatecas,31,031,Monte Escobedo,32031
2427,32,32,Zacatecas,32,032,Morelos,32032
2428,32,32,Zacatecas,33,033,Moyahua de Estrada,32033
2429,32,32,Zacatecas,34,034,Nochistlán de Mejía,32034
2430,32,32,Zacatecas,35,035,Noria de Ángeles,32035
2431,32,32,Zacatecas,36,036,Ojocaliente,32036
2432,32,32,Zacatecas,37,037,Pánuco,32037
2433,32,32,Zacatecas,38,038,Pinos,32038
2434,32,32,Zacatecas,39,039,Río Grande,32039
2435,32,32,Zacatecas,40,040,Sain Alto,32040
2436,32,32,Zacatecas,41,041,El Salvador,32041
2437,32,32,Zacatecas,42,042,Sombrerete,32042
2438,32,32,Zacatecas,43,043,Susticacán,32043
2439,32,32,Zacatecas,44,044,Tabasco,32044
2440,32,32,Zacatecas,45,045,Tepechitlán,32045
2441,32,32,Zacatecas,46,046,Tepetongo,32046
2442,32,32,Zacatecas,47,047,Teúl de González Ortega,32047
2443,32,32,Zacatecas,48,048,Tlaltenango de Sánchez Román,32048
2444,32,32,Zacatecas,49,049,Valparaíso,32049
2445,32,32,Zacatecas,50,050,Vetagrande,32050
2446,32,32,Zacatecas,51,051,Villa de Cos,32051
2447,32,32,Zacatecas,52,052,Villa García,32052
2448,32,32,Zacatecas,53,053,Villa González Ortega,32053
2449,32,32,Zacatecas,54,054,Villa Hidalgo,32054
2450,32,32,Zacatecas,55,055,Villanueva,32055
2451,32,32,Zacatecas,56,056,Zacatecas,32056
2452,32,32,Zacatecas,57,057,Trancoso,32057
2453,32,32,Zacatecas,58,058,Santa María de la Paz,32058
2454,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [129]:
cvemun = cvemun.dropna(how='any')

In [130]:
cvemun

,EDO,cve_ent,nom_ent,MPIO,cve_mun,nom_mun,CVE_MUN_COMP
0,1,01,Aguascalientes,1,001,Aguascalientes,01001
1,1,01,Aguascalientes,2,002,Asientos,01002
2,1,01,Aguascalientes,3,003,Calvillo,01003
3,1,01,Aguascalientes,4,004,Cosío,01004
4,1,01,Aguascalientes,5,005,Jesús María,01005
5,1,01,Aguascalientes,6,006,Pabellón de Arteaga,01006
6,1,01,Aguascalientes,7,007,Rincón de Romos,01007
7,1,01,Aguascalientes,8,008,San José de Gracia,01008
8,1,01,Aguascalientes,9,009,Tepezalá,01009
9,1,01,Aguascalientes,10,010,El Llano,01010
10,1,01,Aguascalientes,11,011,San Francisco de los Romo,01011
11,2,02,Baja California,1,001,Ensenada,02001
12,2,02,Baja California,2,002,Mexicali,02002
13,2,02,Baja California,3,003,Tecate,02003
14,2,02,Baja California,4,004,Tijuana,02004
15,2,02,Baja California,5,005,Playas de Rosarito,02005
16,3,03,Baja California Sur,1,001,Comondú,03001
17,3,03,Baja California Sur,2,002,Mulegé,03002
18,3,03,Baja California Sur,3,003,La Paz,03003
19,3,03,Baja California Sur,8,008,Los Cabos,03008
20,3,03,Baja California Sur,9,009,Loreto,03009
21,4,04,Campeche,1,001,Calkiní,04001
22,4,04,Campeche,2,002,Campeche,04002
23,4,04,Campeche,3,003,Carmen,04003
24,4,04,Campeche,4,004,Champotón,04004
25,4,04,Campeche,5,005,Hecelchakán,04005
26,4,04,Campeche,6,006,Hopelchén,04006
27,4,04,Campeche,7,007,Palizada,04007
28,4,04,Campeche,8,008,Tenabo,04008
29,4,04,Campeche,9,009,Escárcega,04009
...,...,...,...,...,...,...,...
2424,32,32,Zacatecas,29,029,Miguel Auza,32029
2425,32,32,Zacatecas,30,030,Momax,32030
2426,32,32,Zacatecas,31,031,Monte Escobedo,32031
2427,32,32,Zacatecas,32,032,Morelos,32032
2428,32,32,Zacatecas,33,033,Moyahua de Estrada,32033
2429,32,32,Zacatecas,34,034,Nochistlán de Mejía,32034
2430,32,32,Zacatecas,35,035,Noria de Ángeles,32035
2431,32,32,Zacatecas,36,036,Ojocaliente,32036
2432,32,32,Zacatecas,37,037,Pánuco,32037
2433,32,32,Zacatecas,38,038,Pinos,32038
2434,32,32,Zacatecas,39,039,Río Grande,32039
2435,32,32,Zacatecas,40,040,Sain Alto,32040
2436,32,32,Zacatecas,41,041,El Salvador,32041
2437,32,32,Zacatecas,42,042,Sombrerete,32042
2438,32,32,Zacatecas,43,043,Susticacán,32043
2439,32,32,Zacatecas,44,044,Tabasco,32044
2440,32,32,Zacatecas,45,045,Tepechitlán,32045
2441,32,32,Zacatecas,46,046,Tepetongo,32046
2442,32,32,Zacatecas,47,047,Teúl de González Ortega,32047
2443,32,32,Zacatecas,48,048,Tlaltenango de Sánchez Román,32048
2444,32,32,Zacatecas,49,049,Valparaíso,32049
2445,32,32,Zacatecas,50,050,Vetagrande,32050
2446,32,32,Zacatecas,51,051,Villa de Cos,32051
2447,32,32,Zacatecas,52,052,Villa García,32052
2448,32,32,Zacatecas,53,053,Villa González Ortega,32053
2449,32,32,Zacatecas,54,054,Villa Hidalgo,32054
2450,32,32,Zacatecas,55,055,Villanueva,32055
2451,32,32,Zacatecas,56,056,Zacatecas,32056
2452,32,32,Zacatecas,57,057,Trancoso,32057
2453,32,32,Zacatecas,58,058,Santa María de la Paz,32058

In [131]:
accidentesnacional.count()

EDO                1852183
MES                1852183
ANIO               1852183
MPIO               1852183
HORA               1852183
MINUTOS            1852183
DIA                1852183
DIASEMANA          1852183
URBANA             1852183
SUBURBANA          1852183
TIPACCID           1852183
AUTOMOVIL          1852183
CAMPASAJ           1852183
MICROBUS           1852183
PASCAMION          1852183
OMNIBUS            1852183
TRANVIA            1852183
CAMIONETA          1852183
CAMION             1852183
TRACTOR            1852183
FERROCARRI         1852183
MOTOCICLET         1852183
BICICLETA          1852183
OTROVEHIC          1852183
CAUSAACCI          1852183
CAPAROD            1852183
SEXO               1852183
ALIENTO            1852183
CINTURON           1852183
EDAD               1852183
CONDMUERTO         1852183
CONDHERIDO         1852183
PASAMUERTO         1852183
PASAHERIDO         1852183
PEATMUERTO         1852183
PEATHERIDO         1852183
CICLMUERTO         1852183
CICLHERIDO         1852183
OTROMUERTO         1852183
OTROHERIDO         1852183
NEMUERTO           1852183
NEHERIDO           1852183
DIAs               1852183
MESs               1852183
ANIOs              1852183
fechaaccidente     1852183
fechaaccidentes    1852183
feriadopranio      1852183
Feriadodummy       1852183
Feriadotipo        1852183
dtype: int64

In [134]:
accidentesnacional["EDO"]=accidentesnacional["EDO"].astype(str)

In [139]:
accidentesnacional["EDO"].value_counts()

19    401592
14    168084
8     147376
11     95051
2      75724
5      72934
26     69574
22     68235
28     67203
15     63435
9      62077
16     60738
21     47038
17     45896
30     44778
25     42586
23     32629
6      29579
31     28905
10     28658
24     23827
1      20163
20     19624
3      19062
12     18808
4      18101
13     17416
29     14779
27     13210
7      12972
32     12437
18      9692
Name: EDO, dtype: int64

In [135]:
basenacCVE=pd.merge(accidentesnacional,clavesedo,on='EDO',how="left")

In [136]:
basenacCVE.head()

,EDO,MES,ANIO,MPIO,HORA,MINUTOS,DIA,DIASEMANA,URBANA,SUBURBANA,...,DIAs,MESs,ANIOs,fechaaccidente,fechaaccidentes,feriadopranio,Feriadodummy,Feriadotipo,cve_ent,nom_ent
0,1,1,2014,5,20,30,2,4,0,2,...,2,1,2014,2/1/2014,2/1/2014,Vaciones fin de año 2014,Feriado,Vaciones fin de año,01,Aguascalientes
1,1,1,2014,5,9,15,3,5,1,0,...,3,1,2014,3/1/2014,3/1/2014,Vaciones fin de año 2014,Feriado,Vaciones fin de año,01,Aguascalientes
2,1,1,2014,5,9,0,3,5,1,0,...,3,1,2014,3/1/2014,3/1/2014,Vaciones fin de año 2014,Feriado,Vaciones fin de año,01,Aguascalientes
3,1,1,2014,5,9,0,3,5,1,0,...,3,1,2014,3/1/2014,3/1/2014,Vaciones fin de año 2014,Feriado,Vaciones fin de año,01,Aguascalientes
4,1,1,2014,5,23,20,5,7,2,0,...,5,1,2014,5/1/2014,5/1/2014,Vaciones fin de año 2014,Feriado,Vaciones fin de año,01,Aguascalientes

In [138]:
basenacCVE.count()

EDO                1852183
MES                1852183
ANIO               1852183
MPIO               1852183
HORA               1852183
MINUTOS            1852183
DIA                1852183
DIASEMANA          1852183
URBANA             1852183
SUBURBANA          1852183
TIPACCID           1852183
AUTOMOVIL          1852183
CAMPASAJ           1852183
MICROBUS           1852183
PASCAMION          1852183
OMNIBUS            1852183
TRANVIA            1852183
CAMIONETA          1852183
CAMION             1852183
TRACTOR            1852183
FERROCARRI         1852183
MOTOCICLET         1852183
BICICLETA          1852183
OTROVEHIC          1852183
CAUSAACCI          1852183
CAPAROD            1852183
SEXO               1852183
ALIENTO            1852183
CINTURON           1852183
EDAD               1852183
CONDMUERTO         1852183
CONDHERIDO         1852183
PASAMUERTO         1852183
PASAHERIDO         1852183
PEATMUERTO         1852183
PEATHERIDO         1852183
CICLMUERTO         1852183
CICLHERIDO         1852183
OTROMUERTO         1852183
OTROHERIDO         1852183
NEMUERTO           1852183
NEHERIDO           1852183
DIAs               1852183
MESs               1852183
ANIOs              1852183
fechaaccidente     1852183
fechaaccidentes    1852183
feriadopranio      1852183
Feriadodummy       1852183
Feriadotipo        1852183
cve_ent            1852183
nom_ent            1852183
dtype: int64

In [143]:
basenacCVE.groupby("EDO")["nom_ent"].value_counts()

EDO  nom_ent
1    Aguascalientes                      20163
10   Durango                             28658
11   Guanajuato                          95051
12   Guerrero                            18808
13   Hidalgo                             17416
14   Jalisco                            168084
15   México                              63435
16   Michoacán de Ocampo                 60738
17   Morelos                             45896
18   Nayarit                              9692
19   Nuevo León                         401592
2    Baja California                     75724
20   Oaxaca                              19624
21   Puebla                              47038
22   Querétaro                           68235
23   Quintana Roo                        32629
24   San Luis Potosí                     23827
25   Sinaloa                             42586
26   Sonora                              69574
27   Tabasco                             13210
28   Tamaulipas                          67203
29   Tlaxcala                            14779
3    Baja California Sur                 19062
30   Veracruz de Ignacio de la Llave     44778
31   Yucatán                             28905
32   Zacatecas                           12437
4    Campeche                            18101
5    Coahuila de Zaragoza                72934
6    Colima                              29579
7    Chiapas                             12972
8    Chihuahua                          147376
9    Ciudad de México                    62077
Name: nom_ent, dtype: int64

In [148]:
basenacCVE["EDO"]=basenacCVE["EDO"].astype(str)
basenacCVE["MPIO"]=basenacCVE["MPIO"].astype(str)

In [149]:
basenacCVEF=pd.merge(basenacCVE,cvemun,on=['EDO','MPIO'],how="left")

In [150]:
basenacCVEF.head()

,EDO,MES,ANIO,MPIO,HORA,MINUTOS,DIA,DIASEMANA,URBANA,SUBURBANA,...,feriadopranio,Feriadodummy,Feriadotipo,cve_ent_x,nom_ent_x,cve_ent_y,nom_ent_y,cve_mun,nom_mun,CVE_MUN_COMP
0,1,1,2014,5,20,30,2,4,0,2,...,Vaciones fin de año 2014,Feriado,Vaciones fin de año,01,Aguascalientes,01,Aguascalientes,005,Jesús María,01005
1,1,1,2014,5,9,15,3,5,1,0,...,Vaciones fin de año 2014,Feriado,Vaciones fin de año,01,Aguascalientes,01,Aguascalientes,005,Jesús María,01005
2,1,1,2014,5,9,0,3,5,1,0,...,Vaciones fin de año 2014,Feriado,Vaciones fin de año,01,Aguascalientes,01,Aguascalientes,005,Jesús María,01005
3,1,1,2014,5,9,0,3,5,1,0,...,Vaciones fin de año 2014,Feriado,Vaciones fin de año,01,Aguascalientes,01,Aguascalientes,005,Jesús María,01005
4,1,1,2014,5,23,20,5,7,2,0,...,Vaciones fin de año 2014,Feriado,Vaciones fin de año,01,Aguascalientes,01,Aguascalientes,005,Jesús María,01005

In [151]:
basenacCVEF.count()

EDO                1852183
MES                1852183
ANIO               1852183
MPIO               1852183
HORA               1852183
MINUTOS            1852183
DIA                1852183
DIASEMANA          1852183
URBANA             1852183
SUBURBANA          1852183
TIPACCID           1852183
AUTOMOVIL          1852183
CAMPASAJ           1852183
MICROBUS           1852183
PASCAMION          1852183
OMNIBUS            1852183
TRANVIA            1852183
CAMIONETA          1852183
CAMION             1852183
TRACTOR            1852183
FERROCARRI         1852183
MOTOCICLET         1852183
BICICLETA          1852183
OTROVEHIC          1852183
CAUSAACCI          1852183
CAPAROD            1852183
SEXO               1852183
ALIENTO            1852183
CINTURON           1852183
EDAD               1852183
CONDMUERTO         1852183
CONDHERIDO         1852183
PASAMUERTO         1852183
PASAHERIDO         1852183
PEATMUERTO         1852183
PEATHERIDO         1852183
CICLMUERTO         1852183
CICLHERIDO         1852183
OTROMUERTO         1852183
OTROHERIDO         1852183
NEMUERTO           1852183
NEHERIDO           1852183
DIAs               1852183
MESs               1852183
ANIOs              1852183
fechaaccidente     1852183
fechaaccidentes    1852183
feriadopranio      1852183
Feriadodummy       1852183
Feriadotipo        1852183
cve_ent_x          1852183
nom_ent_x          1852183
cve_ent_y          1850567
nom_ent_y          1850567
cve_mun            1850567
nom_mun            1850567
CVE_MUN_COMP       1850567
dtype: int64

In [152]:
basenacCVEF.to_csv('baseaacidentesconclave.csv')

In [2]:
import pandas as pd

In [12]:
accidentescclave=pd.read_csv("baseaacidentesconclave.csv",dtype=str)

In [16]:
accidentescclave.dtypes

Unnamed: 0         object
EDO                object
MES                object
ANIO               object
MPIO               object
HORA               object
MINUTOS            object
DIA                object
DIASEMANA          object
URBANA             object
SUBURBANA          object
TIPACCID           object
AUTOMOVIL          object
CAMPASAJ           object
MICROBUS           object
PASCAMION          object
OMNIBUS            object
TRANVIA            object
CAMIONETA          object
CAMION             object
TRACTOR            object
FERROCARRI         object
MOTOCICLET         object
BICICLETA          object
OTROVEHIC          object
CAUSAACCI          object
CAPAROD            object
SEXO               object
ALIENTO            object
CINTURON           object
EDAD               object
CONDMUERTO         object
CONDHERIDO         object
PASAMUERTO         object
PASAHERIDO         object
PEATMUERTO         object
PEATHERIDO         object
CICLMUERTO         object
CICLHERIDO         object
OTROMUERTO         object
OTROHERIDO         object
NEMUERTO           object
NEHERIDO           object
DIAs               object
MESs               object
ANIOs              object
fechaaccidente     object
fechaaccidentes    object
feriadopranio      object
Feriadodummy       object
Feriadotipo        object
cve_ent_x          object
nom_ent_x          object
cve_ent_y          object
nom_ent_y          object
cve_mun            object
nom_mun            object
CVE_MUN_COMP       object
dtype: object

In [13]:
accidentescclave.count()

Unnamed: 0         1852183
EDO                1852183
MES                1852183
ANIO               1852183
MPIO               1852183
HORA               1852183
MINUTOS            1852183
DIA                1852183
DIASEMANA          1852183
URBANA             1852183
SUBURBANA          1852183
TIPACCID           1852183
AUTOMOVIL          1852183
CAMPASAJ           1852183
MICROBUS           1852183
PASCAMION          1852183
OMNIBUS            1852183
TRANVIA            1852183
CAMIONETA          1852183
CAMION             1852183
TRACTOR            1852183
FERROCARRI         1852183
MOTOCICLET         1852183
BICICLETA          1852183
OTROVEHIC          1852183
CAUSAACCI          1852183
CAPAROD            1852183
SEXO               1852183
ALIENTO            1852183
CINTURON           1852183
EDAD               1852183
CONDMUERTO         1852183
CONDHERIDO         1852183
PASAMUERTO         1852183
PASAHERIDO         1852183
PEATMUERTO         1852183
PEATHERIDO         1852183
CICLMUERTO         1852183
CICLHERIDO         1852183
OTROMUERTO         1852183
OTROHERIDO         1852183
NEMUERTO           1852183
NEHERIDO           1852183
DIAs               1852183
MESs               1852183
ANIOs              1852183
fechaaccidente     1852183
fechaaccidentes    1852183
feriadopranio      1852183
Feriadodummy       1852183
Feriadotipo        1852183
cve_ent_x          1852183
nom_ent_x          1852183
cve_ent_y          1850567
nom_ent_y          1850567
cve_mun            1850567
nom_mun            1850567
CVE_MUN_COMP       1850567
dtype: int64

In [17]:
acidentesCLAVE = accidentescclave.filter(['cve_ent_x', 'nom_ent_x','cve_mun','nom_mun','fechaaccidentes','feriadopranio','Feriadodummy','Feriadotipo','DIAs','MESs','ANIOs','DIASEMANA','TIPACCID','CAUSAACCI','SEXO','ALIENTO','EDAD'],axis=1)

In [18]:
acidentesCLAVE.head()

,cve_ent_x,nom_ent_x,cve_mun,nom_mun,fechaaccidentes,feriadopranio,Feriadodummy,Feriadotipo,DIAs,MESs,ANIOs,DIASEMANA,TIPACCID,CAUSAACCI,SEXO,ALIENTO,EDAD
0,01,Aguascalientes,005,Jesús María,2/1/2014,Vaciones fin de año 2014,Feriado,Vaciones fin de año,2,1,2014,4,1,1,2,6,49
1,01,Aguascalientes,005,Jesús María,3/1/2014,Vaciones fin de año 2014,Feriado,Vaciones fin de año,3,1,2014,5,1,1,2,6,49
2,01,Aguascalientes,005,Jesús María,3/1/2014,Vaciones fin de año 2014,Feriado,Vaciones fin de año,3,1,2014,5,1,1,3,6,32
3,01,Aguascalientes,005,Jesús María,3/1/2014,Vaciones fin de año 2014,Feriado,Vaciones fin de año,3,1,2014,5,1,1,2,6,25
4,01,Aguascalientes,005,Jesús María,5/1/2014,Vaciones fin de año 2014,Feriado,Vaciones fin de año,5,1,2014,7,1,1,2,6,43

In [19]:
acidentesCLAVE.count()

cve_ent_x          1852183
nom_ent_x          1852183
cve_mun            1850567
nom_mun            1850567
fechaaccidentes    1852183
feriadopranio      1852183
Feriadodummy       1852183
Feriadotipo        1852183
DIAs               1852183
MESs               1852183
ANIOs              1852183
DIASEMANA          1852183
TIPACCID           1852183
CAUSAACCI          1852183
SEXO               1852183
ALIENTO            1852183
EDAD               1852183
dtype: int64

In [20]:
acidentesCLAVE=acidentesCLAVE.rename(columns = {"cve_ent_x":"INEGI-EST","nom_ent_x":"ESTADO","cve_mun":"INEGI-MUN","nom_mun":"MUNICIPIO",})

In [21]:
acidentesCLAVE.columns

Index(['INEGI-EST', 'ESTADO', 'INEGI-MUN', 'MUNICIPIO', 'fechaaccidentes',
       'feriadopranio', 'Feriadodummy', 'Feriadotipo', 'DIAs', 'MESs', 'ANIOs',
       'DIASEMANA', 'TIPACCID', 'CAUSAACCI', 'SEXO', 'ALIENTO', 'EDAD'],
      dtype='object')

In [22]:
acidentesCLAVE = acidentesCLAVE.dropna(how='any')

In [43]:
acidentesCLAVE["EDAD"].value_counts()

0     203003
99    155305
18     59191
20     57640
30     50580
25     49709
28     47967
26     45607
32     45311
27     45212
23     44774
24     44507
35     43650
29     42750
22     41695
33     40046
34     38317
36     37943
21     37912
31     37535
40     37454
38     37118
42     34294
45     33606
37     33576
39     31933
19     30881
43     28827
41     28350
44     25104
       ...
71      2765
73      2545
74      2425
75      2161
76      1709
14      1567
77      1531
78      1388
80      1162
79      1061
12       774
13       758
82       643
81       637
83       461
84       457
85       376
86       270
87       226
88       154
89       113
90        97
92        43
91        42
93        31
94        27
95        17
98        14
96        10
97         8
Name: EDAD, Length: 89, dtype: int64

In [23]:
acidentesCLAVE.count()

INEGI-EST          1850567
ESTADO             1850567
INEGI-MUN          1850567
MUNICIPIO          1850567
fechaaccidentes    1850567
feriadopranio      1850567
Feriadodummy       1850567
Feriadotipo        1850567
DIAs               1850567
MESs               1850567
ANIOs              1850567
DIASEMANA          1850567
TIPACCID           1850567
CAUSAACCI          1850567
SEXO               1850567
ALIENTO            1850567
EDAD               1850567
dtype: int64

In [24]:
acidentesCLAVE.to_csv("accidentesCLAVE.cvs")

In [27]:
acidentesCLAVE["Feriadotipo"].value_counts()

No feriado                  1730541
Vacaciones fin de año         37005
Vaciones fin de año           19919
Semana Santa                  13044
Independencia de México       10089
Año nuevo                      6316
Dia del trabajo                6076
Nochebuena                     5064
Inicio clases verano           4991
Inicio vacaciones verano       4769
Navidad                        4472
Fin de año                     4171
Batalla de Puebla              4110
Name: Feriadotipo, dtype: int64

In [28]:
acidentesCLAVE=acidentesCLAVE.replace({"Vaciones fin de año": "Vacaciones fin de año", "Inicio clases verano": "Fin vacaiones verano"})

In [29]:
acidentesCLAVE["Feriadotipo"].value_counts()

No feriado                  1730541
Vacaciones fin de año         56924
Semana Santa                  13044
Independencia de México       10089
Año nuevo                      6316
Dia del trabajo                6076
Nochebuena                     5064
Fin vacaiones verano           4991
Inicio vacaciones verano       4769
Navidad                        4472
Fin de año                     4171
Batalla de Puebla              4110
Name: Feriadotipo, dtype: int64

In [30]:
acidentesCLAVE.count()

INEGI-EST          1850567
ESTADO             1850567
INEGI-MUN          1850567
MUNICIPIO          1850567
fechaaccidentes    1850567
feriadopranio      1850567
Feriadodummy       1850567
Feriadotipo        1850567
DIAs               1850567
MESs               1850567
ANIOs              1850567
DIASEMANA          1850567
TIPACCID           1850567
CAUSAACCI          1850567
SEXO               1850567
ALIENTO            1850567
EDAD               1850567
dtype: int64

In [31]:
acidentesCLAVE.to_csv('acidentesCLAVE.csv')

In [40]:
acidentesCLAVE.groupby("ESTADO")["ESTADO"].value_counts()

ESTADO                           ESTADO
Aguascalientes                   Aguascalientes                      20163
Baja California                  Baja California                     75724
Baja California Sur              Baja California Sur                 19062
Campeche                         Campeche                            18101
Chiapas                          Chiapas                             12972
Chihuahua                        Chihuahua                          147318
Ciudad de México                 Ciudad de México                    62077
Coahuila de Zaragoza             Coahuila de Zaragoza                72934
Colima                           Colima                              29579
Durango                          Durango                             28658
Guanajuato                       Guanajuato                          94406
Guerrero                         Guerrero                            18790
Hidalgo                          Hidalgo                             17416
Jalisco                          Jalisco                            167601
Michoacán de Ocampo              Michoacán de Ocampo                 60738
Morelos                          Morelos                             45896
México                           México                              63435
Nayarit                          Nayarit                              9692
Nuevo León                       Nuevo León                         401568
Oaxaca                           Oaxaca                              19624
Puebla                           Puebla                              47038
Querétaro                        Querétaro                           68235
Quintana Roo                     Quintana Roo                        32629
San Luis Potosí                  San Luis Potosí                     23827
Sinaloa                          Sinaloa                             42586
Sonora                           Sonora                              69574
Tabasco                          Tabasco                             13210
Tamaulipas                       Tamaulipas                          66817
Tlaxcala                         Tlaxcala                            14779
Veracruz de Ignacio de la Llave  Veracruz de Ignacio de la Llave     44776
Yucatán                          Yucatán                             28905
Zacatecas                        Zacatecas                           12437
Name: ESTADO, dtype: int64

In [44]:
acidentesCLAVE["CAUSAACCI"].value_counts()

1    1705274
4      57920
5      54549
3      16716
2      16108
Name: CAUSAACCI, dtype: int64

In [45]:
DummyConductor= []
for row in acidentesCLAVE["CAUSAACCI"]:
    if row =="1":
        DummyConductor.append('1')    
    else:
        DummyConductor.append('0')

In [46]:
DummyPeatonpasajero= []
for row in acidentesCLAVE["CAUSAACCI"]:
    if row =="2":
        DummyPeatonpasajero.append('1')    
    else:
        DummyPeatonpasajero.append('0')

In [47]:
DummyFallavehículo= []
for row in acidentesCLAVE["CAUSAACCI"]:
    if row =="3":
        DummyFallavehículo.append('1')    
    else:
        DummyFallavehículo.append('0')

In [58]:
len(DummyFallavehículo)

1850567

In [63]:
Dummycondiccamino= []
for row in acidentesCLAVE["CAUSAACCI"]:
    if row =="4":
        Dummycondiccamino.append('1')    
    else:
        Dummycondiccamino.append('0')

In [64]:
len(Dummycondiccamino)

1850567

In [66]:
Dummyotrascausas= []
for row in acidentesCLAVE["CAUSAACCI"]:
    if row =="5":
        Dummyotrascausas.append('1')    
    else:
        Dummyotrascausas.append('0')

In [67]:
len(Dummyotrascausas)

1850567

In [50]:
acidentesCLAVE['DummyCausaConductor'] = DummyConductor

In [51]:
acidentesCLAVE['DummyCausaPeatonpasajero'] = DummyPeatonpasajero

In [52]:
acidentesCLAVE['DummyCausaFallavehículo'] = DummyFallavehículo

In [68]:
acidentesCLAVE['DummyCausacondiccamino'] = Dummycondiccamino

In [69]:
acidentesCLAVE['DummyCausaotrascausas'] = Dummyotrascausas

In [70]:
acidentesCLAVE.head()

,INEGI-EST,ESTADO,INEGI-MUN,MUNICIPIO,fechaaccidentes,feriadopranio,Feriadodummy,Feriadotipo,DIAs,MESs,...,TIPACCID,CAUSAACCI,SEXO,ALIENTO,EDAD,DummyCausaConductor,DummyCausaPeatonpasajero,DummyCausaFallavehículo,DummyCausacondiccamino,DummyCausaotrascausas
0,01,Aguascalientes,005,Jesús María,2/1/2014,Vaciones fin de año 2014,Feriado,Vacaciones fin de año,2,1,...,1,1,2,6,49,1,0,0,0,0
1,01,Aguascalientes,005,Jesús María,3/1/2014,Vaciones fin de año 2014,Feriado,Vacaciones fin de año,3,1,...,1,1,2,6,49,1,0,0,0,0
2,01,Aguascalientes,005,Jesús María,3/1/2014,Vaciones fin de año 2014,Feriado,Vacaciones fin de año,3,1,...,1,1,3,6,32,1,0,0,0,0
3,01,Aguascalientes,005,Jesús María,3/1/2014,Vaciones fin de año 2014,Feriado,Vacaciones fin de año,3,1,...,1,1,2,6,25,1,0,0,0,0
4,01,Aguascalientes,005,Jesús María,5/1/2014,Vaciones fin de año 2014,Feriado,Vacaciones fin de año,5,1,...,1,1,2,6,43,1,0,0,0,0

In [71]:
acidentesCLAVE.count()

INEGI-EST                   1850567
ESTADO                      1850567
INEGI-MUN                   1850567
MUNICIPIO                   1850567
fechaaccidentes             1850567
feriadopranio               1850567
Feriadodummy                1850567
Feriadotipo                 1850567
DIAs                        1850567
MESs                        1850567
ANIOs                       1850567
DIASEMANA                   1850567
TIPACCID                    1850567
CAUSAACCI                   1850567
SEXO                        1850567
ALIENTO                     1850567
EDAD                        1850567
DummyCausaConductor         1850567
DummyCausaPeatonpasajero    1850567
DummyCausaFallavehículo     1850567
DummyCausacondiccamino      1850567
DummyCausaotrascausas       1850567
dtype: int64

In [72]:
acidentesCLAVE.to_csv('acidentesCLAVEVF.csv')

In [75]:
acidentesCLAVE["ANIOs"]=acidentesCLAVE["ANIOs"].astype(int)

In [77]:
acidentesCLAVE["ANIOs"].value_counts()

2014    380298
2015    378345
2017    367379
2018    364825
2016    359720
Name: ANIOs, dtype: int64

In [2]:
import pandas as pd

In [3]:
acidentesCLAVE=pd.read_csv("acidentesCLAVEVF.csv",dtype=str)

In [5]:
acidentesCLAVE.count()

Unnamed: 0                  1850567
INEGI-EST                   1850567
ESTADO                      1850567
INEGI-MUN                   1850567
MUNICIPIO                   1850567
fechaaccidentes             1850567
feriadopranio               1850567
Feriadodummy                1850567
Feriadotipo                 1850567
DIAs                        1850567
MESs                        1850567
ANIOs                       1850567
DIASEMANA                   1850567
TIPACCID                    1850567
CAUSAACCI                   1850567
SEXO                        1850567
ALIENTO                     1850567
EDAD                        1850567
DummyCausaConductor         1850567
DummyCausaPeatonpasajero    1850567
DummyCausaFallavehículo     1850567
DummyCausacondiccamino      1850567
DummyCausaotrascausas       1850567
dtype: int64

In [8]:
acidentesCLAVE["INEGI-MUN"].value_counts()

039    236414
019    111328
006     73146
004     58174
005     57512
014     54725
046     51337
001     49363
018     43672
007     42362
002     41717
017     41234
020     39040
021     38555
003     37391
120     36410
037     35790
026     34965
053     33476
035     32378
033     30756
030     28607
114     28409
048     25966
010     23505
032     23075
027     22046
028     21306
011     21215
009     20431
        ...
306         1
424         1
539         1
366         1
434         1
229         1
519         1
391         1
242         1
543         1
349         1
301         1
243         1
331         1
235         1
447         1
557         1
300         1
284         1
417         1
313         1
254         1
262         1
491         1
273         1
226         1
272         1
530         1
402         1
561         1
Name: INEGI-MUN, Length: 335, dtype: int64

In [9]:
acidentesCLAVE['CVE_MUN_COMP'] = acidentesCLAVE["INEGI-EST"]+ acidentesCLAVE["INEGI-MUN"]

In [10]:
acidentesCLAVE.count()

Unnamed: 0                  1850567
INEGI-EST                   1850567
ESTADO                      1850567
INEGI-MUN                   1850567
MUNICIPIO                   1850567
fechaaccidentes             1850567
feriadopranio               1850567
Feriadodummy                1850567
Feriadotipo                 1850567
DIAs                        1850567
MESs                        1850567
ANIOs                       1850567
DIASEMANA                   1850567
TIPACCID                    1850567
CAUSAACCI                   1850567
SEXO                        1850567
ALIENTO                     1850567
EDAD                        1850567
DummyCausaConductor         1850567
DummyCausaPeatonpasajero    1850567
DummyCausaFallavehículo     1850567
DummyCausacondiccamino      1850567
DummyCausaotrascausas       1850567
CVE_MUN_COMP                1850567
dtype: int64

In [12]:
RESTMUN14VF=pd.read_csv("RESTMUN2014df.csv",dtype=str)
RESTMUN15VF=pd.read_csv("RESTMUN2015df.csv",dtype=str)
RESTMUN16VF=pd.read_csv("RESTMUN2016df.csv",dtype=str)
RESTMUN17VF=pd.read_csv("RESTMUN2017df.csv",dtype=str)
RESTMUN18VF=pd.read_csv("RESTMUN2018df.csv",dtype=str)
BARESMUN14VF=pd.read_csv("BARESMUN2014df.csv",dtype=str)
BARESMUN15VF=pd.read_csv("BARESMUN2015df.csv",dtype=str)
BARESMUN16VF=pd.read_csv("BARESMUN2016df.csv",dtype=str)
BARESMUN17VF=pd.read_csv("BARESMUN2017df.csv",dtype=str)
BARESMUN18VF=pd.read_csv("BARESMUN2018df.csv",dtype=str)
SALONESFIESTAMUN14VF=pd.read_csv("SALONESFIESTA2014df.csv",dtype=str)
SALONESFIESTAMUN15VF=pd.read_csv("SALONESFIESTA2015df.csv",dtype=str)
SALONESFIESTAMUN16VF=pd.read_csv("SALONESFIESTA2016df.csv",dtype=str)
SALONESFIESTAMUN17VF=pd.read_csv("SALONESFIESTA2017df.csv",dtype=str)
SALONESFIESTAMUN18VF=pd.read_csv("SALONESFIESTA2018df.csv",dtype=str)
PLAZASMUN14VF=pd.read_csv("PLAZAS2014df.csv",dtype=str)
PLAZASMUN15VF=pd.read_csv("PLAZAS2015df.csv",dtype=str)
PLAZASMUN16VF=pd.read_csv("PLAZAS2016df.csv",dtype=str)
PLAZASMUN17VF=pd.read_csv("PLAZAS2017df.csv",dtype=str)
PLAZASMUN18VF=pd.read_csv("PLAZAS2018df.csv",dtype=str)

In [15]:
RESTMUN14VF.columns

Index(['CVE_MUN_COMP', 'RESTMUN14'], dtype='object')

In [17]:
acidentesCLAVE=pd.merge(acidentesCLAVE,RESTMUN14VF,on='CVE_MUN_COMP',how="left")

In [18]:
acidentesCLAVE.count()

Unnamed: 0                  1850567
INEGI-EST                   1850567
ESTADO                      1850567
INEGI-MUN                   1850567
MUNICIPIO                   1850567
fechaaccidentes             1850567
feriadopranio               1850567
Feriadodummy                1850567
Feriadotipo                 1850567
DIAs                        1850567
MESs                        1850567
ANIOs                       1850567
DIASEMANA                   1850567
TIPACCID                    1850567
CAUSAACCI                   1850567
SEXO                        1850567
ALIENTO                     1850567
EDAD                        1850567
DummyCausaConductor         1850567
DummyCausaPeatonpasajero    1850567
DummyCausaFallavehículo     1850567
DummyCausacondiccamino      1850567
DummyCausaotrascausas       1850567
CVE_MUN_COMP                1850567
RESTMUN14                   1850259
dtype: int64

In [19]:
acidentesCLAVE=pd.merge(acidentesCLAVE,RESTMUN15VF,on='CVE_MUN_COMP',how="left")
acidentesCLAVE=pd.merge(acidentesCLAVE,RESTMUN16VF,on='CVE_MUN_COMP',how="left")
acidentesCLAVE=pd.merge(acidentesCLAVE,RESTMUN17VF,on='CVE_MUN_COMP',how="left")
acidentesCLAVE=pd.merge(acidentesCLAVE,RESTMUN18VF,on='CVE_MUN_COMP',how="left")
acidentesCLAVE=pd.merge(acidentesCLAVE,BARESMUN14VF,on='CVE_MUN_COMP',how="left")
acidentesCLAVE=pd.merge(acidentesCLAVE,BARESMUN15VF,on='CVE_MUN_COMP',how="left")
acidentesCLAVE=pd.merge(acidentesCLAVE,BARESMUN16VF,on='CVE_MUN_COMP',how="left")
acidentesCLAVE=pd.merge(acidentesCLAVE,BARESMUN17VF,on='CVE_MUN_COMP',how="left")
acidentesCLAVE=pd.merge(acidentesCLAVE,BARESMUN18VF,on='CVE_MUN_COMP',how="left")
acidentesCLAVE=pd.merge(acidentesCLAVE,SALONESFIESTAMUN14VF,on='CVE_MUN_COMP',how="left")
acidentesCLAVE=pd.merge(acidentesCLAVE,SALONESFIESTAMUN15VF,on='CVE_MUN_COMP',how="left")
acidentesCLAVE=pd.merge(acidentesCLAVE,SALONESFIESTAMUN16VF,on='CVE_MUN_COMP',how="left")
acidentesCLAVE=pd.merge(acidentesCLAVE,SALONESFIESTAMUN17VF,on='CVE_MUN_COMP',how="left")
acidentesCLAVE=pd.merge(acidentesCLAVE,SALONESFIESTAMUN18VF,on='CVE_MUN_COMP',how="left")
acidentesCLAVE=pd.merge(acidentesCLAVE,PLAZASMUN14VF,on='CVE_MUN_COMP',how="left")
acidentesCLAVE=pd.merge(acidentesCLAVE,PLAZASMUN15VF,on='CVE_MUN_COMP',how="left")
acidentesCLAVE=pd.merge(acidentesCLAVE,PLAZASMUN16VF,on='CVE_MUN_COMP',how="left")
acidentesCLAVE=pd.merge(acidentesCLAVE,PLAZASMUN17VF,on='CVE_MUN_COMP',how="left")
acidentesCLAVE=pd.merge(acidentesCLAVE,PLAZASMUN18VF,on='CVE_MUN_COMP',how="left")

In [20]:
acidentesCLAVE.count()

Unnamed: 0                  1850567
INEGI-EST                   1850567
ESTADO                      1850567
INEGI-MUN                   1850567
MUNICIPIO                   1850567
fechaaccidentes             1850567
feriadopranio               1850567
Feriadodummy                1850567
Feriadotipo                 1850567
DIAs                        1850567
MESs                        1850567
ANIOs                       1850567
DIASEMANA                   1850567
TIPACCID                    1850567
CAUSAACCI                   1850567
SEXO                        1850567
ALIENTO                     1850567
EDAD                        1850567
DummyCausaConductor         1850567
DummyCausaPeatonpasajero    1850567
DummyCausaFallavehículo     1850567
DummyCausacondiccamino      1850567
DummyCausaotrascausas       1850567
CVE_MUN_COMP                1850567
RESTMUN14                   1850259
RESTMUN15                   1850259
RESTMUN16                   1850260
RESTMUN17                   1850260
RESTMUN18                   1850260
BARESMUN14                  1836241
BARESMUN15                  1836241
BARESMUN16                  1836244
BARESMUN17                  1836244
BARESMUN18                  1836244
SALONESFIESTA14             1833033
SALONESFIESTA15             1833033
SALONESFIESTA16             1833054
SALONESFIESTA17             1833095
SALONESFIESTA18             1833095
PLAZAS14                    1677055
PLAZAS15                    1677055
PLAZAS16                    1697978
PLAZAS17                    1704828
PLAZAS18                    1704985
dtype: int64

In [22]:
acidentesCLAVE["BARESMUN14"].value_counts()

339    161190
16      71002
406     65500
42      59503
183     56666
118     42732
30      40787
222     39620
128     36375
2       33485
63      32660
231     32505
26      29966
139     29236
233     28703
79      28507
296     28066
74      25933
21      25703
14      25180
7       24535
91      24016
152     23694
33      22471
58      22014
27      21823
53      20453
23      19402
47      19137
294     19091
        ...
65       4049
109      3882
262      3430
101      3374
282      3065
83       2948
162      2924
73       2847
186      2464
59       2319
39       2291
104      2054
84       1991
24       1851
41       1693
55       1421
28       1386
35       1036
141       825
93        741
61        623
102       369
108       308
54        191
62        140
87        124
95        115
50         66
68         50
116        21
Name: BARESMUN14, Length: 127, dtype: int64

In [23]:
acidentesCLAVE["BARESMUN14"] = acidentesCLAVE["BARESMUN14"].fillna("0")

In [28]:
acidentesCLAVE["BARESMUN15"] = acidentesCLAVE["BARESMUN15"].fillna("0")
acidentesCLAVE["BARESMUN16"] = acidentesCLAVE["BARESMUN16"].fillna("0")
acidentesCLAVE["BARESMUN17"] = acidentesCLAVE["BARESMUN17"].fillna("0")
acidentesCLAVE["BARESMUN18"] = acidentesCLAVE["BARESMUN18"].fillna("0")
acidentesCLAVE["RESTMUN14"] = acidentesCLAVE["RESTMUN14"].fillna("0")
acidentesCLAVE["RESTMUN15"] = acidentesCLAVE["RESTMUN15"].fillna("0")
acidentesCLAVE["RESTMUN16"] = acidentesCLAVE["RESTMUN16"].fillna("0")
acidentesCLAVE["RESTMUN18"] = acidentesCLAVE["RESTMUN18"].fillna("0")
acidentesCLAVE["RESTMUN17"] = acidentesCLAVE["RESTMUN17"].fillna("0")
acidentesCLAVE["SALONESFIESTA14"] = acidentesCLAVE["SALONESFIESTA14"].fillna("0")
acidentesCLAVE["SALONESFIESTA15"] = acidentesCLAVE["SALONESFIESTA15"].fillna("0")
acidentesCLAVE["SALONESFIESTA16"] = acidentesCLAVE["SALONESFIESTA16"].fillna("0")
acidentesCLAVE["SALONESFIESTA17"] = acidentesCLAVE["SALONESFIESTA17"].fillna("0")
acidentesCLAVE["SALONESFIESTA18"] = acidentesCLAVE["SALONESFIESTA18"].fillna("0")
acidentesCLAVE["PLAZAS14"] = acidentesCLAVE["PLAZAS14"].fillna("0")
acidentesCLAVE["PLAZAS15"] = acidentesCLAVE["PLAZAS15"].fillna("0")
acidentesCLAVE["PLAZAS16"] = acidentesCLAVE["PLAZAS16"].fillna("0")
acidentesCLAVE["PLAZAS17"] = acidentesCLAVE["PLAZAS17"].fillna("0")
acidentesCLAVE["PLAZAS18"] = acidentesCLAVE["PLAZAS18"].fillna("0")

In [30]:
acidentesCLAVE.count()

Unnamed: 0                  1850567
INEGI-EST                   1850567
ESTADO                      1850567
INEGI-MUN                   1850567
MUNICIPIO                   1850567
fechaaccidentes             1850567
feriadopranio               1850567
Feriadodummy                1850567
Feriadotipo                 1850567
DIAs                        1850567
MESs                        1850567
ANIOs                       1850567
DIASEMANA                   1850567
TIPACCID                    1850567
CAUSAACCI                   1850567
SEXO                        1850567
ALIENTO                     1850567
EDAD                        1850567
DummyCausaConductor         1850567
DummyCausaPeatonpasajero    1850567
DummyCausaFallavehículo     1850567
DummyCausacondiccamino      1850567
DummyCausaotrascausas       1850567
CVE_MUN_COMP                1850567
RESTMUN14                   1850567
RESTMUN15                   1850567
RESTMUN16                   1850567
RESTMUN17                   1850567
RESTMUN18                   1850567
BARESMUN14                  1850567
BARESMUN15                  1850567
BARESMUN16                  1850567
BARESMUN17                  1850567
BARESMUN18                  1850567
SALONESFIESTA14             1850567
SALONESFIESTA15             1850567
SALONESFIESTA16             1850567
SALONESFIESTA17             1850567
SALONESFIESTA18             1850567
PLAZAS14                    1850567
PLAZAS15                    1850567
PLAZAS16                    1850567
PLAZAS17                    1850567
PLAZAS18                    1850567
dtype: int64

In [31]:
acidentesCLAVE.to_csv("accidentesNacVF.csv")